version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
install:
- cmd: >-
    git submodule update --init --recursive

    premake5 vs2022
cache: build
before_build:
- cmd: before_build.bat
build:
  project: build/Win64.WidescreenFixesPack.sln
  parallel: true
  verbosity: minimal
before_package:
- cmd: >-
    msbuild -m build/PCSX2F.WidescreenFixesPack.sln /p:Configuration=Release

    msbuild -m build/PPSSPP.WidescreenFixesPack.sln /p:Configuration=Release

    msbuild -m build/Dolphin.WidescreenFixesPack.sln /p:Configuration=Release

    msbuild -m build/CXBXR.WidescreenFixesPack.sln /p:Configuration=Release


    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Bully_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:CallOfCthulhu_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ColdFear_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Condemned_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:DeerAvenger4_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Driv3r_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:DriverParallelLines_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:EnterTheMatrix_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:FarCry_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTA1_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTA2_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTA3_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTASA_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTAVC_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Gun_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:HiddenandDangerous2_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:JustCause_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:KingKong_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:KnightRider_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:KnightRider2_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:LARush_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Mafia_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Manhunt_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:MaxPayne\\MaxPayne_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:MaxPayne\\MaxPayne2_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSCarbon_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSMostWanted_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSProStreet_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSUnderground_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSUnderground2_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSUndercover_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSTheRun_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Onimusha3_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ParadiseCracked_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:PsiOpsTheMindgateConspiracy_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Psychonauts_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ThePunisher_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil0_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil5_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil6_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvilRevelations_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvilRevelations2_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCell_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Scarface_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellConviction_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellBlacklist_FusionFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellChaosTheory_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellDoubleAgent_WidescreenFix /p:Configuration=Release

    msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellPandoraTomorrow_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SecondSight_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SilentHill\\SilentHill2_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SilentHill\\SilentHill3_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SilentHill\\SilentHill4_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SniperElite_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SonicHeroes_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:StreetRacingSyndicate_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheGodfather_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheMatrixPathOfNeo_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheSaboteur_FusionFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheSuffering_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksProSkater2_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksProSkater3_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksProSkater4_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksUnderground_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksUnderground2_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksAmericanWasteland_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TotalOverdose_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TrueCrimeNewYorkCity_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TrueCrimeStreetsofLA_WidescreenFix /p:Configuration=Release

    REM msbuild -m build/Win32.WidescreenFixesPack.slnx /t:UltimateSpiderMan_WidescreenFix /p:Configuration=Release



    before_packaging.bat

    cd data

    release.bat
after_build:
- ps: Get-ChildItem .\Archives\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }