version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5 vs2022
before_build:
- cmd: REM before_build.bat
build:
  project: build/Win32.WidescreenFixesPack.sln
  verbosity: minimal
before_package:
- cmd: >-
    msbuild -m build/Win64.WidescreenFixesPack.sln /p:Configuration=Release

    REM msbuild -m build/PCSX2F.WidescreenFixesPack.sln /p:Configuration=Release

    REM msbuild -m build/PPSSPP.WidescreenFixesPack.sln /p:Configuration=Release

    REM msbuild -m build/Dolphin.WidescreenFixesPack.sln /p:Configuration=Release

    REM msbuild -m build/CXBXR.WidescreenFixesPack.sln /p:Configuration=Release


    REM before_packaging.bat

    cd data

    release.bat
after_build:
- ps: Get-ChildItem .\Archives\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }