name: "Build By Tag"
description: "Pushes built artifacts to specified release"

inputs:
  token:
    description: "Github's token"
    required: true
  tag:
    description: "Tag of release on github"
    required: true
  tag_list:
    description: "List of tags needed to release this time"
    required: true
  artifacts:
    description: "List of artifacts for release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if tag matches
      id: tag_requires_updating
      shell: bash
      run: |
        IFS=',' read -ra TAGS <<< "${{ inputs.tag_list }}"
        for t in "${TAGS[@]}"; do
          if [ "$t" = "all" ] || [ "$t" = "${{ inputs.tag }}" ]; then
            echo "split_value=True" >> "$GITHUB_OUTPUT"
            echo "readme_path=.github/docs/${{ inputs.tag }}.md" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        done
    - name: Get release info
      if: ${{ steps.tag_requires_updating.outputs.split_value == 'True' }}
      id: release_info
      uses: cardinalby/git-get-release-action@1.2.4
      env:
       GITHUB_TOKEN: ${{ inputs.token }}
      with:
        tag: ${{ inputs.tag }}
    - name: Upload Release
      if: ${{ steps.tag_requires_updating.outputs.split_value == 'True' }}
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.token }}
        allowUpdates: true
        makeLatest: true
        name: ${{ steps.release_info.outputs.name }}
#        body: ${{ steps.release_info.outputs.body }}
        bodyFile: ${{ steps.tag_requires_updating.outputs.readme_path }}
        tag: ${{ steps.release_info.outputs.tag_name }}
        artifacts: ${{ inputs.artifacts }}
