name: "Build All"

inputs:
  project:
    description: "Full msbuild command(s) to run (or empty to build everything)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Configure build
      shell: cmd
      run: |
        ./premake5.bat

    - name: Before Build
      shell: cmd
      run: |
        ./before_build.bat

    - name: Build
      shell: cmd
      run: |
        if "${{ inputs.project }}" == "" (
          echo Building ALL solutions...
          msbuild -m build/Win32.WidescreenFixesPack.slnx /p:Configuration=Release
          msbuild -m build/Win64.WidescreenFixesPack.slnx /p:Configuration=Release
          msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /p:Configuration=Release
          msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /p:Configuration=Release
          msbuild -m build/Dolphin.WidescreenFixesPack.slnx /p:Configuration=Release
          msbuild -m build/CXBXR.WidescreenFixesPack.slnx /p:Configuration=Release
        ) else (
          echo Building specific tag...
          ${{ inputs.project }}
        )

    - name: Before Package
      shell: cmd
      run: |
        ./before_packaging.bat

    - name: Pack binaries
      shell: cmd
      run: |
        cd ./data
        release.bat

    - name: Upload artifacts to actions
      if: ${{ inputs.project == '' }}
      uses: actions/upload-artifact@v7
      with:
        name: WidescreenFixesPack
        path: ./data/Archives/*.zip