# Regenerates source/Shared/Console/PCButtonArtwork.hpp from the PNGs in this folder.
# Each image becomes one 16-byte aligned PS2 texture block: PSMT8 pixels followed by
# a 256-entry CT32 CLUT, already in the GS CSM1 order and the PS2 alpha range
# (0x80 = opaque). The plugins hand these blocks to the native raster code as-is.
from pathlib import Path
from PIL import Image
root = Path(__file__).resolve().parents[2]
src = Path(__file__).resolve().parent
# (file, identifier, Windows virtual-key codes). Mouse codes follow the Windows
# VK numbering (1 LMB, 2 RMB, 4 MMB, 5/6 X buttons); 0x0E/0x0F are the wheel
# (unassigned VKs) and 0x07 is the display-only "mouse movement" icon.
keys = [
    ('LMB', 'LMB', [0x01]), ('RMB', 'RMB', [0x02]), ('MMB', 'MMB', [0x04]),
    ('MOUSE4', 'MOUSE4', [0x05]), ('MOUSE5', 'MOUSE5', [0x06]), ('MOUSE', 'MOUSE', [0x07]),
    ('MWHU', 'WHEELUP', [0x0E]), ('MWHD', 'WHEELDOWN', [0x0F]),
    ('BACKSP', 'BACKSP', [0x08]), ('TAB', 'TAB', [0x09]), ('enter', 'ENTER', [0x0D]),
    ('SHIFT', 'SHIFT', [0x10]), ('LCTRL', 'CTRL', [0x11]), ('ALT', 'ALT', [0x12]),
    ('pause', 'PAUSE', [0x13]), ('CAPSLK', 'CAPSLK', [0x14]), ('ESC', 'ESC', [0x1B]),
    ('SPACEBAR', 'SPACEBAR', [0x20]), ('PGUP', 'PGUP', [0x21]), ('PGDN', 'PGDN', [0x22]),
    ('END', 'END', [0x23]), ('HOME', 'HOME', [0x24]), ('LEFT', 'LEFT', [0x25]), ('UP', 'UP', [0x26]),
    ('RIGHT', 'RIGHT', [0x27]), ('DOWN', 'DOWN', [0x28]), ('print', 'PRINT', [0x2C]),
    ('INS', 'INS', [0x2D]), ('DEL', 'DEL', [0x2E]),
] + [(str(d), 'KEY%d' % d, [0x30 + d]) for d in range(10)] \
  + [(chr(c), chr(c), [c]) for c in range(ord('A'), ord('Z') + 1)] + [
    ('LWIN', 'LWIN', [0x5B]), ('RWIN', 'RWIN', [0x5C]), ('APPS', 'APPS', [0x5D]),
    ('padins', 'NUM0', [0x60]), ('padend', 'NUM1', [0x61]), ('paddown', 'NUM2', [0x62]),
    ('padpgdn', 'NUM3', [0x63]), ('padleft', 'NUM4', [0x64]), ('pad5', 'NUM5', [0x65]),
    ('padright', 'NUM6', [0x66]), ('padhome', 'NUM7', [0x67]), ('padup', 'NUM8', [0x68]),
    ('padpgup', 'NUM9', [0x69]), ('TIMES', 'MULTIPLY', [0x6A]), ('PLUS', 'PLUS', [0x6B]),
    ('DIVIDE', 'DIVIDE', [0x6F]),
] + [('F%d' % i, 'F%d' % i, [0x6F + i]) for i in range(1, 13)] + [
    ('NUMLOCK', 'NUMLOCK', [0x90]), ('SCROLL', 'SCROLL', [0x91]),
    ('SEMICOLON', 'SEMICOLON', [0xBA]), ('EQUAL', 'EQUAL', [0xBB]), ('COMMA', 'COMMA', [0xBC]),
    ('MINUS', 'MINUS', [0xBD, 0x6D]), ('DOT', 'DOT', [0xBE]), ('BACKTICK', 'BACKTICK', [0xC0]),
    ('BRACKETL', 'BRACKETL', [0xDB]), ('BACKSLASH', 'BACKSLASH', [0xDC]),
    ('BRACKETR', 'BRACKETR', [0xDD]), ('APOSTROPHE', 'APOSTROPHE', [0xDE]),
]

def texture(name):
    im = Image.open(src / (name + '.png')).convert('RGBA')
    if im.height != 64:  # TAB is 99x66: keep the 64-texel row budget
        im = im.resize((round(im.width * 64 / im.height), 64), Image.LANCZOS)
    w = 1 << (im.width - 1).bit_length()
    pad = Image.new('RGBA', (w, 64)); pad.paste(im, (0, 0))
    q = pad.quantize(colors=256, method=Image.Quantize.FASTOCTREE)
    pal = q.getpalette('RGBA'); pal = pal + [0] * (1024 - len(pal))
    clut = [0] * 256
    for j in range(256):
        r, g, b, a = pal[4 * j:4 * j + 4]
        csm = (j & ~24) | ((j & 8) << 1) | ((j & 16) >> 1)
        clut[csm] = r | g << 8 | b << 16 | ((a + 1) // 2) << 24
    data = bytes(q.tobytes()) + b''.join(c.to_bytes(4, 'little') for c in clut)
    return w, im.width, data

out = ['#pragma once\n#include <cstdint>\n',
       '// Generated by resources/pc-buttons/generate.py. Do not edit.\n',
       '// Each texture: PSMT8 pixels (width x 64) followed by a CSM1-ordered\n',
       '// 256-entry CT32 CLUT with PS2 alpha (0x80 opaque).\n',
       'namespace console::pcbuttons {\n',
       'enum class Key : uint8_t { ' + ', '.join(k[1] for k in keys) + ', Count };\n',
       'struct Artwork { const uint8_t* data; uint16_t width, contentWidth; };\n',
       'constexpr unsigned height = 64, log2Height = 6;\n']
index = [0xFF] * 256
for i, (name, ident, vks) in enumerate(keys):
    w, content, data = texture(name)
    for vk in vks: index[vk] = i
    out.append(f'alignas(16) inline constexpr uint8_t texture{ident}[]={{\n')
    for o in range(0, len(data), 128):
        out.append(','.join(str(x) for x in data[o:o + 128]) + ',\n')
    out.append('};\n')
    keys[i] = (name, ident, vks, w, content)
out.append('inline constexpr Artwork artwork[]={\n' +
           ''.join(f'{{texture{k[1]},{k[3]},{k[4]}}},\n' for k in keys) + '};\n')
out.append('// Virtual-key code to artwork index; 0xFF = no artwork.\n')
out.append('inline constexpr uint8_t keyArtwork[256]={' + ','.join(str(x) for x in index) + '};\n')
out.append('inline const Artwork* Find(unsigned vk) {\n'
           '    return vk < 256 && keyArtwork[vk] != 0xFF ? &artwork[keyArtwork[vk]] : nullptr;\n}\n')
out.append('constexpr unsigned Log2(unsigned value) { unsigned r = 0; while ((1u << r) < value) ++r; return r; }\n}\n')
target = root / 'source/Shared/Console/PCButtonArtwork.hpp'
target.write_text(''.join(out), newline='\n')
print(target, target.stat().st_size, len(keys), 'textures')
