HWND hWnd;
uint32_t ResX, ResY;
RsGlobalType* RsGlobal;
float fWideScreenWidthScaleDown, fWideScreenHeightScaleDown;
float fHudWidthScale, fHudHeightScale;
float fSubtitlesScale;
float fCustomWideScreenWidthScaleDown;
float fCustomWideScreenHeightScaleDown;
uint32_t AspectRatioWidth, AspectRatioHeight;
float fCustomAspectRatioHor, fCustomAspectRatioVer;
float fRadarWidthScale, fCustomRadarWidthScale;
float fPlayerMarkerPos;
char *szForceAspectRatio;
bool bFOVControl;
float fEmergencyVehiclesFix;
float fFOVControlValue;
uint32_t* FOVControl;
float fCarSpeedDependantFOV;
float fRadarScaling;
float fCrosshairPosFactor;
uint32_t nHideAABug;
float fCrosshairHeightScaleDown;
bool bIVRadarScaling;
uint32_t ReplaceTextShadowWithOutline;
float fCustomRadarWidthIV;
float fCustomRadarHeightIV;
float fCustomRadarPosXIV;
float fCustomRadarPosYIV;
float fCustomRadarRingWidthIV;
float fCustomRadarRingHeightIV;
float fCustomRadarRingPosXIV;
float fCustomRadarRingPosYIV;
float fCustomRadarRingPosXIV2;
uint32_t SelectedMultisamplingLevels;
uint32_t* BordersVar1;
uint32_t* BordersVar2;
bool* bWideScreen;
bool* bIsInCutscene;
bool bRestoreCutsceneFOV;
bool bDontTouchFOV;
bool bSmallerTextShadows;
bool bSmartCutsceneBorders;
bool bAllowAltTabbingWithoutPausing;
int(__cdecl* CSprite2dDrawRect)(class CRect const &, class CRGBA const &);
int(__cdecl* FindPlayerVehicle)();
void(__thiscall *funcCCameraAvoidTheGeometry)(void* _this, RwV3d const&, RwV3d const&, RwV3d&, float);