#pragma once
// Generated by tools/vehicle-lights/generate.py from textures/GTAVCS. Do not edit.
#include "../Shared/Console/VehicleLights.hpp"
namespace vehicle {
// Light rectangles in texels of the reference size (inclusive bounds).
inline constexpr console::LightRect lightRects[] = {
    // vcs_6atvbit
    {27, 100, 28, 112, console::LightTailReverse}, {30, 100, 30, 112, console::LightTailReverse}, {24, 101, 26, 112, console::LightTailReverse}, {29, 101, 29, 112, console::LightTailReverse},
    {31, 101, 33, 112, console::LightTailReverse}, {21, 102, 23, 112, console::LightTailReverse}, {34, 102, 34, 112, console::LightTailReverse}, {20, 103, 20, 112, console::LightTailReverse},
    {35, 103, 35, 112, console::LightTailReverse}, {19, 104, 19, 104, console::LightTailReverse}, {19, 106, 19, 112, console::LightTailReverse}, {2, 113, 18, 113, console::LightHead},
    {23, 113, 23, 113, console::LightReverse}, {25, 113, 25, 113, console::LightReverse}, {27, 113, 27, 113, console::LightReverse}, {29, 113, 29, 113, console::LightReverse},
    {31, 113, 34, 113, console::LightReverse}, {4, 114, 15, 116, console::LightHead}, {3, 115, 3, 127, console::LightHead}, {16, 115, 17, 126, console::LightHead},
    {2, 116, 2, 127, console::LightHead}, {18, 116, 18, 126, console::LightHead}, {4, 117, 13, 118, console::LightHead}, {15, 117, 15, 127, console::LightHead},
    {1, 118, 1, 118, console::LightHead}, {4, 119, 9, 127, console::LightHead}, {11, 119, 14, 127, console::LightHead}, {1, 120, 1, 126, console::LightHead},
    {10, 120, 10, 120, console::LightHead}, {10, 122, 10, 127, console::LightHead}, {16, 127, 16, 127, console::LightHead},
    // admiral868bit_sl
    {32, 0, 47, 31, console::LightTailReverse}, {49, 1, 62, 14, console::LightHead}, {16, 16, 16, 21, console::LightReverse}, {17, 16, 31, 31, console::LightTailReverse},
    {48, 16, 48, 21, console::LightReverse}, {16, 22, 16, 30, console::LightTailReverse}, {48, 22, 48, 23, console::LightBrake}, {48, 24, 48, 29, console::LightTailReverse},
    {48, 30, 48, 31, console::LightReverse}, {16, 31, 16, 31, console::LightBrake}, {113, 49, 126, 62, console::LightHead},
    // vicechee868bit128
    {112, 96, 123, 99, console::LightHead}, {112, 100, 115, 110, console::LightHead}, {117, 100, 123, 102, console::LightHead}, {116, 101, 116, 101, console::LightHead},
    {116, 103, 116, 103, console::LightHead}, {118, 103, 123, 103, console::LightHead}, {120, 104, 123, 110, console::LightHead}, {116, 105, 116, 105, console::LightHead},
    {118, 105, 119, 110, console::LightHead}, {117, 106, 117, 110, console::LightHead}, {116, 107, 116, 110, console::LightHead}, {112, 112, 115, 112, console::LightReverse},
    {116, 112, 127, 127, console::LightTailReverse}, {112, 113, 115, 113, console::LightTailReverse}, {112, 114, 115, 114, console::LightBrake}, {112, 115, 115, 115, console::LightTailReverse},
    {112, 116, 114, 116, console::LightBrake}, {115, 116, 115, 125, console::LightTailReverse}, {112, 117, 114, 117, console::LightTailReverse}, {112, 118, 113, 118, console::LightBrake},
    {114, 118, 114, 123, console::LightTailReverse}, {112, 119, 113, 123, console::LightTailReverse}, {112, 124, 114, 124, console::LightBrake}, {112, 125, 114, 125, console::LightTailReverse},
    {112, 126, 115, 126, console::LightBrake}, {112, 127, 115, 127, console::LightTailReverse},
    // baggage8bit128
    {64, 64, 79, 70, console::LightHead}, {65, 71, 71, 71, console::LightHead}, {76, 71, 78, 71, console::LightHead}, {96, 111, 111, 127, console::LightHead},
    {118, 111, 118, 111, console::LightBrake}, {120, 111, 125, 111, console::LightBrake}, {112, 112, 127, 127, console::LightTailReverse},
    // banshee868bit_sl
    {96, 0, 111, 31, console::LightHead}, {112, 16, 127, 31, console::LightTailReverse},
    // iz_perennial_interior
    {113, 97, 126, 109, console::LightTailReverse}, {96, 112, 111, 126, console::LightHead}, {96, 127, 105, 127, console::LightHead}, {108, 127, 111, 127, console::LightHead},
    // blistac868bit_sl
    {86, 15, 101, 30, console::LightHead}, {64, 31, 68, 36, console::LightTailReverse}, {69, 31, 72, 31, console::LightBrake}, {73, 31, 73, 31, console::LightReverse},
    {74, 31, 74, 31, console::LightBrake}, {75, 31, 86, 46, console::LightTailReverse}, {87, 31, 87, 31, console::LightBrake}, {88, 31, 95, 46, console::LightTailReverse},
    {96, 31, 98, 31, console::LightBrake}, {99, 31, 104, 46, console::LightTailReverse}, {105, 31, 105, 31, console::LightBrake}, {106, 31, 110, 31, console::LightReverse},
    {111, 31, 113, 44, console::LightTailReverse}, {117, 31, 117, 31, console::LightBrake}, {118, 31, 119, 44, console::LightTailReverse}, {123, 31, 125, 45, console::LightTailReverse},
    {69, 32, 74, 46, console::LightTailReverse}, {87, 32, 87, 46, console::LightTailReverse}, {96, 32, 98, 46, console::LightTailReverse}, {105, 32, 110, 44, console::LightTailReverse},
    {114, 32, 117, 46, console::LightTailReverse}, {120, 32, 122, 46, console::LightTailReverse}, {126, 32, 127, 34, console::LightTailReverse}, {126, 35, 126, 44, console::LightTailReverse},
    {127, 35, 127, 35, console::LightBrake}, {127, 36, 127, 42, console::LightTailReverse}, {64, 37, 65, 37, console::LightReverse}, {66, 37, 68, 42, console::LightTailReverse},
    {64, 38, 65, 38, console::LightTailReverse}, {64, 39, 65, 39, console::LightReverse}, {64, 40, 65, 40, console::LightTailReverse}, {64, 41, 65, 41, console::LightReverse},
    {64, 42, 65, 42, console::LightTailReverse}, {64, 43, 65, 43, console::LightReverse}, {66, 43, 66, 43, console::LightBrake}, {67, 43, 68, 46, console::LightTailReverse},
    {64, 44, 66, 44, console::LightTailReverse}, {127, 44, 127, 44, console::LightTailReverse}, {64, 45, 66, 46, console::LightReverse}, {105, 45, 108, 46, console::LightTailReverse},
    {109, 45, 109, 45, console::LightBrake}, {110, 45, 111, 45, console::LightReverse}, {112, 45, 113, 46, console::LightTailReverse}, {109, 46, 111, 46, console::LightTailReverse},
    {118, 46, 119, 46, console::LightTailReverse}, {123, 46, 124, 46, console::LightTailReverse}, {125, 46, 125, 46, console::LightBrake},
    // vcs_bobcatbit
    {114, 65, 123, 85, console::LightTailReverse}, {124, 65, 125, 65, console::LightBrake}, {113, 66, 113, 93, console::LightTailReverse}, {124, 66, 125, 93, console::LightTailReverse},
    {114, 86, 114, 93, console::LightTailReverse}, {115, 86, 123, 91, console::LightReverse}, {115, 92, 123, 93, console::LightTailReverse}, {112, 96, 127, 110, console::LightHead},
    {112, 111, 126, 111, console::LightHead},
    // vcs_dozerbit2
    {111, 35, 117, 60, console::LightTailReverse}, {118, 36, 119, 62, console::LightTailReverse}, {110, 37, 110, 51, console::LightTailReverse}, {120, 37, 120, 63, console::LightTailReverse},
    {109, 38, 109, 51, console::LightTailReverse}, {121, 38, 121, 38, console::LightTail}, {121, 39, 121, 62, console::LightTailReverse}, {108, 40, 108, 51, console::LightTailReverse},
    {122, 40, 122, 40, console::LightTail}, {122, 41, 122, 61, console::LightTailReverse}, {107, 42, 107, 51, console::LightTailReverse}, {123, 43, 123, 63, console::LightTailReverse},
    {106, 47, 106, 47, console::LightTailReverse}, {124, 48, 124, 48, console::LightTailReverse}, {106, 50, 106, 51, console::LightTailReverse}, {124, 50, 124, 51, console::LightTailReverse},
    {124, 53, 124, 54, console::LightTailReverse}, {124, 56, 124, 57, console::LightTailReverse}, {105, 59, 105, 60, console::LightTailReverse}, {124, 59, 124, 59, console::LightTailReverse},
    {112, 61, 117, 62, console::LightTailReverse}, {124, 61, 124, 61, console::LightTailReverse}, {105, 62, 105, 64, console::LightTailReverse}, {112, 63, 112, 63, console::LightTailReverse},
    {114, 63, 114, 63, console::LightTailReverse}, {116, 63, 116, 63, console::LightTailReverse}, {118, 63, 118, 63, console::LightTailReverse}, {124, 63, 124, 64, console::LightTailReverse},
    {104, 64, 104, 64, console::LightTailReverse}, {113, 64, 122, 68, console::LightReverse}, {111, 65, 112, 65, console::LightTailReverse}, {111, 67, 112, 72, console::LightTailReverse},
    {105, 68, 105, 69, console::LightTailReverse}, {106, 69, 109, 69, console::LightTailReverse}, {118, 69, 118, 72, console::LightTailReverse}, {120, 69, 120, 72, console::LightTailReverse},
    {123, 69, 123, 70, console::LightTailReverse}, {107, 70, 110, 72, console::LightTailReverse}, {113, 70, 117, 72, console::LightTailReverse}, {119, 70, 119, 72, console::LightTailReverse},
    {121, 70, 122, 72, console::LightTailReverse}, {105, 72, 106, 72, console::LightTailReverse}, {123, 72, 123, 72, console::LightTailReverse},
    // burritobit
    {106, 47, 119, 48, console::LightTailReverse}, {106, 49, 117, 60, console::LightTailReverse}, {118, 49, 118, 58, console::LightReverse}, {119, 49, 119, 49, console::LightTailReverse},
    {119, 50, 119, 58, console::LightReverse}, {118, 59, 119, 60, console::LightTailReverse}, {15, 65, 29, 80, console::LightHead}, {40, 65, 55, 80, console::LightHead},
    {30, 66, 30, 80, console::LightHead},
    // cabbie8bit
    {61, 3, 62, 3, console::LightReverse}, {65, 3, 66, 24, console::LightHead}, {69, 3, 70, 3, console::LightReverse}, {59, 4, 60, 4, console::LightReverse},
    {61, 4, 64, 23, console::LightHead}, {67, 4, 71, 23, console::LightHead}, {72, 4, 72, 4, console::LightReverse}, {58, 5, 58, 5, console::LightReverse},
    {59, 5, 60, 22, console::LightHead}, {72, 5, 72, 22, console::LightHead}, {73, 5, 73, 5, console::LightReverse}, {57, 6, 57, 6, console::LightReverse},
    {58, 6, 58, 21, console::LightHead}, {73, 6, 73, 21, console::LightHead}, {74, 6, 74, 6, console::LightReverse}, {57, 7, 57, 20, console::LightHead},
    {74, 7, 74, 20, console::LightHead}, {56, 8, 56, 8, console::LightReverse}, {75, 8, 75, 8, console::LightReverse}, {97, 8, 112, 13, console::LightTail},
    {113, 8, 126, 13, console::LightReverse}, {56, 9, 56, 19, console::LightHead}, {75, 9, 75, 19, console::LightHead}, {76, 9, 76, 10, console::LightReverse},
    {55, 10, 55, 10, console::LightReverse}, {55, 11, 55, 15, console::LightHead}, {76, 11, 76, 16, console::LightHead}, {76, 17, 76, 17, console::LightReverse},
    {75, 20, 75, 20, console::LightReverse}, {57, 21, 57, 21, console::LightReverse}, {74, 21, 74, 21, console::LightReverse}, {58, 22, 58, 22, console::LightReverse},
    {73, 22, 73, 22, console::LightReverse}, {60, 23, 60, 23, console::LightReverse}, {72, 23, 72, 23, console::LightReverse}, {62, 24, 62, 24, console::LightReverse},
    {63, 24, 64, 24, console::LightHead}, {67, 24, 68, 24, console::LightHead}, {69, 24, 69, 24, console::LightReverse}, {72, 63, 81, 63, console::LightReverse},
    {83, 63, 87, 63, console::LightReverse}, {72, 64, 77, 68, console::LightReverse}, {80, 64, 80, 65, console::LightReverse}, {85, 64, 87, 66, console::LightReverse},
    {78, 65, 79, 73, console::LightReverse}, {81, 65, 82, 65, console::LightReverse}, {82, 66, 82, 66, console::LightReverse}, {81, 67, 81, 78, console::LightReverse},
    {84, 67, 85, 67, console::LightReverse}, {87, 67, 87, 71, console::LightReverse}, {80, 68, 80, 73, console::LightReverse}, {82, 68, 83, 71, console::LightReverse},
    {85, 68, 86, 71, console::LightReverse}, {72, 69, 72, 78, console::LightReverse}, {74, 69, 77, 72, console::LightReverse}, {84, 69, 84, 74, console::LightReverse},
    {73, 70, 73, 78, console::LightReverse}, {83, 72, 83, 78, console::LightReverse}, {85, 72, 85, 78, console::LightReverse}, {74, 73, 75, 78, console::LightReverse},
    {77, 73, 77, 74, console::LightReverse}, {82, 73, 82, 74, console::LightReverse}, {79, 74, 79, 74, console::LightReverse}, {76, 76, 80, 76, console::LightReverse},
    {82, 76, 82, 78, console::LightReverse}, {84, 76, 84, 76, console::LightReverse}, {76, 77, 77, 78, console::LightReverse}, {79, 77, 80, 78, console::LightReverse},
    {86, 77, 87, 78, console::LightReverse}, {78, 78, 78, 78, console::LightReverse}, {84, 78, 84, 78, console::LightReverse},
    // caddy8bit128
    {96, 112, 111, 126, console::LightHead}, {112, 112, 125, 120, console::LightTailReverse}, {126, 112, 126, 112, console::LightBrake}, {127, 112, 127, 112, console::LightReverse},
    {126, 113, 127, 125, console::LightTailReverse}, {112, 121, 112, 123, console::LightBrake}, {113, 121, 125, 125, console::LightTailReverse}, {112, 124, 112, 126, console::LightTailReverse},
    {113, 126, 117, 126, console::LightTailReverse}, {118, 126, 120, 126, console::LightBrake}, {121, 126, 124, 126, console::LightReverse}, {125, 126, 126, 126, console::LightTailReverse},
    {127, 126, 127, 126, console::LightBrake}, {96, 127, 105, 127, console::LightHead}, {108, 127, 111, 127, console::LightHead}, {112, 127, 116, 127, console::LightReverse},
    // pimpbit
    {8, 2, 13, 8, console::LightHead}, {44, 2, 50, 5, console::LightReverse}, {6, 3, 7, 12, console::LightHead}, {14, 3, 15, 11, console::LightHead},
    {42, 3, 43, 6, console::LightReverse}, {51, 3, 52, 6, console::LightReverse}, {5, 4, 5, 11, console::LightHead}, {16, 4, 16, 8, console::LightHead},
    {41, 4, 41, 7, console::LightReverse}, {53, 4, 53, 7, console::LightReverse}, {4, 5, 4, 11, console::LightHead}, {17, 5, 17, 8, console::LightHead},
    {40, 5, 40, 8, console::LightReverse}, {54, 5, 54, 7, console::LightReverse}, {3, 6, 3, 15, console::LightHead}, {18, 6, 18, 15, console::LightHead},
    {39, 6, 39, 15, console::LightReverse}, {44, 6, 44, 6, console::LightReverse}, {45, 6, 50, 17, console::LightTailReverse}, {55, 6, 55, 15, console::LightReverse},
    {42, 7, 44, 15, console::LightTailReverse}, {51, 7, 52, 16, console::LightTailReverse}, {2, 8, 2, 13, console::LightHead}, {19, 8, 19, 13, console::LightHead},
    {38, 8, 38, 14, console::LightReverse}, {41, 8, 41, 15, console::LightTailReverse}, {53, 8, 54, 14, console::LightTailReverse}, {56, 8, 56, 14, console::LightReverse},
    {8, 9, 9, 10, console::LightHead}, {12, 9, 13, 10, console::LightHead}, {40, 9, 40, 12, console::LightTailReverse}, {16, 10, 16, 17, console::LightHead},
    {8, 11, 8, 11, console::LightHead}, {13, 11, 13, 19, console::LightHead}, {17, 11, 17, 16, console::LightHead}, {11, 12, 12, 19, console::LightHead},
    {14, 12, 14, 18, console::LightHead}, {4, 13, 4, 16, console::LightHead}, {9, 13, 10, 13, console::LightHead}, {15, 13, 15, 15, console::LightHead},
    {40, 13, 40, 16, console::LightReverse}, {5, 15, 5, 17, console::LightHead}, {53, 15, 53, 15, console::LightTailReverse}, {54, 15, 54, 16, console::LightReverse},
    {6, 16, 6, 17, console::LightHead}, {41, 16, 42, 16, console::LightReverse}, {43, 16, 44, 16, console::LightTailReverse}, {53, 16, 53, 17, console::LightReverse},
    {7, 17, 7, 18, console::LightHead}, {15, 17, 15, 18, console::LightHead}, {42, 17, 43, 17, console::LightReverse}, {44, 17, 44, 17, console::LightTailReverse},
    {51, 17, 52, 18, console::LightReverse}, {8, 18, 10, 19, console::LightHead}, {43, 18, 50, 18, console::LightReverse}, {45, 19, 50, 19, console::LightReverse},
    // deluxobit
    {22, 56, 22, 71, console::LightReverse}, {38, 56, 53, 58, console::LightHead}, {23, 57, 37, 57, console::LightReverse}, {23, 58, 25, 62, console::LightTailReverse},
    {26, 58, 33, 58, console::LightReverse}, {34, 58, 36, 58, console::LightTailReverse}, {37, 58, 37, 59, console::LightReverse}, {26, 59, 35, 66, console::LightTailReverse},
    {36, 59, 36, 62, console::LightReverse}, {38, 59, 41, 61, console::LightHead}, {43, 59, 53, 59, console::LightHead}, {44, 60, 46, 60, console::LightHead},
    {48, 60, 48, 60, console::LightHead}, {50, 60, 53, 61, console::LightHead}, {37, 61, 37, 71, console::LightReverse}, {44, 61, 45, 71, console::LightHead},
    {47, 61, 47, 71, console::LightHead}, {49, 61, 49, 61, console::LightHead}, {38, 62, 39, 71, console::LightHead}, {41, 62, 41, 71, console::LightHead},
    {43, 62, 43, 62, console::LightHead}, {46, 62, 46, 71, console::LightHead}, {48, 62, 48, 71, console::LightHead}, {50, 62, 50, 63, console::LightHead},
    {52, 62, 53, 62, console::LightHead}, {23, 63, 23, 63, console::LightReverse}, {24, 63, 25, 66, console::LightTailReverse}, {36, 63, 36, 63, console::LightTailReverse},
    {40, 63, 40, 71, console::LightHead}, {42, 63, 42, 63, console::LightHead}, {49, 63, 49, 71, console::LightHead}, {53, 63, 53, 71, console::LightHead},
    {23, 64, 23, 64, console::LightTailReverse}, {36, 64, 36, 64, console::LightReverse}, {43, 64, 43, 71, console::LightHead}, {52, 64, 52, 71, console::LightHead},
    {23, 65, 23, 66, console::LightReverse}, {36, 65, 36, 66, console::LightTailReverse}, {42, 65, 42, 71, console::LightHead}, {50, 66, 50, 66, console::LightHead},
    {23, 67, 24, 68, console::LightTailReverse}, {25, 67, 25, 67, console::LightReverse}, {26, 67, 31, 67, console::LightTailReverse}, {32, 67, 32, 67, console::LightReverse},
    {33, 67, 35, 69, console::LightTailReverse}, {36, 67, 36, 71, console::LightReverse}, {25, 68, 26, 70, console::LightTailReverse}, {27, 68, 27, 68, console::LightReverse},
    {28, 68, 29, 68, console::LightTailReverse}, {30, 68, 31, 68, console::LightReverse}, {32, 68, 32, 69, console::LightTailReverse}, {50, 68, 50, 71, console::LightHead},
    {23, 69, 23, 69, console::LightReverse}, {24, 69, 24, 70, console::LightTailReverse}, {27, 69, 27, 70, console::LightTailReverse}, {28, 69, 28, 71, console::LightReverse},
    {29, 69, 31, 69, console::LightTailReverse}, {51, 69, 51, 71, console::LightHead}, {23, 70, 23, 70, console::LightTailReverse}, {29, 70, 34, 70, console::LightReverse},
    {35, 70, 35, 70, console::LightTailReverse}, {23, 71, 26, 71, console::LightReverse}, {29, 71, 29, 71, console::LightReverse}, {32, 71, 34, 71, console::LightReverse},
    // esperanto
    {16, 5, 30, 5, console::LightTailReverse}, {31, 5, 31, 6, console::LightReverse}, {16, 6, 16, 6, console::LightReverse}, {17, 6, 30, 11, console::LightTailReverse},
    {16, 7, 16, 7, console::LightTailReverse}, {31, 7, 31, 7, console::LightTailReverse}, {16, 8, 16, 12, console::LightReverse}, {31, 8, 31, 9, console::LightReverse},
    {31, 10, 31, 10, console::LightTailReverse}, {31, 11, 31, 12, console::LightReverse}, {17, 12, 17, 12, console::LightReverse}, {19, 12, 21, 12, console::LightReverse},
    {22, 12, 22, 12, console::LightTailReverse}, {23, 12, 23, 12, console::LightReverse}, {24, 12, 24, 12, console::LightTailReverse}, {25, 12, 26, 12, console::LightReverse},
    {27, 12, 27, 12, console::LightTailReverse}, {28, 12, 28, 12, console::LightReverse}, {29, 12, 29, 12, console::LightTailReverse}, {30, 12, 30, 12, console::LightReverse},
    {8, 15, 14, 16, console::LightHead}, {8, 17, 12, 17, console::LightHead}, {14, 17, 14, 21, console::LightHead}, {8, 18, 10, 21, console::LightHead},
    {12, 19, 12, 21, console::LightHead}, {11, 20, 11, 21, console::LightHead}, {13, 20, 13, 21, console::LightHead},
    // vc_vehicledoors_sl
    {81, 1, 95, 4, console::LightHead}, {97, 1, 110, 3, console::LightHead}, {97, 4, 99, 15, console::LightHead}, {101, 4, 110, 4, console::LightHead},
    {81, 5, 84, 15, console::LightHead}, {87, 5, 95, 15, console::LightHead}, {102, 5, 110, 15, console::LightHead}, {85, 6, 85, 15, console::LightHead},
    {101, 6, 101, 15, console::LightHead}, {86, 7, 86, 15, console::LightHead}, {100, 7, 100, 15, console::LightHead}, {81, 17, 95, 19, console::LightHead},
    {97, 17, 110, 18, console::LightHead}, {97, 19, 98, 22, console::LightHead}, {103, 19, 110, 22, console::LightHead}, {81, 20, 83, 22, console::LightHead},
    {87, 20, 88, 22, console::LightHead}, {90, 20, 95, 22, console::LightHead}, {84, 21, 86, 22, console::LightHead}, {89, 21, 89, 22, console::LightHead},
    {99, 21, 102, 22, console::LightHead}, {89, 25, 110, 30, console::LightTailReverse}, {112, 25, 126, 25, console::LightTailReverse}, {112, 26, 123, 29, console::LightReverse},
    {124, 26, 126, 30, console::LightTailReverse}, {112, 30, 123, 30, console::LightTailReverse}, {112, 50, 125, 61, console::LightTailReverse},
    // firetruk8bit128
    {96, 96, 110, 110, console::LightHead}, {111, 96, 111, 97, console::LightReverse}, {112, 96, 125, 104, console::LightTailReverse}, {126, 96, 127, 96, console::LightBrake},
    {126, 97, 127, 109, console::LightTailReverse}, {111, 98, 111, 99, console::LightHead}, {111, 100, 111, 101, console::LightReverse}, {111, 102, 111, 105, console::LightHead},
    {112, 105, 112, 107, console::LightBrake}, {113, 105, 125, 109, console::LightTailReverse}, {111, 106, 111, 109, console::LightReverse}, {112, 108, 112, 110, console::LightTailReverse},
    {111, 110, 111, 110, console::LightHead}, {113, 110, 117, 110, console::LightTailReverse}, {118, 110, 120, 110, console::LightBrake}, {121, 110, 124, 110, console::LightReverse},
    {125, 110, 126, 110, console::LightTailReverse}, {127, 110, 127, 110, console::LightBrake}, {96, 111, 103, 126, console::LightHead}, {111, 111, 116, 111, console::LightReverse},
    {104, 112, 127, 115, console::LightHead}, {108, 116, 115, 119, console::LightHead}, {120, 116, 127, 116, console::LightHead}, {121, 117, 127, 126, console::LightHead},
    {104, 119, 107, 119, console::LightHead}, {116, 119, 118, 119, console::LightHead}, {120, 119, 120, 120, console::LightHead}, {106, 120, 107, 120, console::LightHead},
    {109, 120, 115, 121, console::LightHead}, {105, 121, 105, 123, console::LightHead}, {117, 121, 117, 123, console::LightHead}, {104, 122, 104, 123, console::LightHead},
    {107, 122, 114, 123, console::LightHead}, {116, 122, 116, 123, console::LightHead}, {118, 122, 120, 122, console::LightHead}, {115, 123, 115, 127, console::LightHead},
    {118, 123, 118, 123, console::LightHead}, {120, 123, 120, 126, console::LightHead}, {108, 124, 114, 126, console::LightHead}, {107, 125, 107, 125, console::LightHead},
    {97, 127, 103, 127, console::LightHead}, {109, 127, 114, 127, console::LightHead}, {121, 127, 126, 127, console::LightHead},
    // glendale_main64x64
    {32, 32, 47, 46, console::LightHead}, {48, 32, 48, 32, console::LightReverse}, {49, 32, 62, 41, console::LightTailReverse}, {63, 32, 63, 32, console::LightReverse},
    {48, 33, 48, 35, console::LightBrake}, {63, 33, 63, 37, console::LightBrake}, {48, 36, 48, 46, console::LightTailReverse}, {63, 38, 63, 47, console::LightReverse},
    {49, 42, 61, 47, console::LightTailReverse}, {62, 42, 62, 42, console::LightBrake}, {62, 43, 62, 46, console::LightTailReverse}, {32, 47, 39, 47, console::LightHead},
    {44, 47, 47, 47, console::LightHead}, {48, 47, 48, 47, console::LightReverse}, {62, 47, 62, 47, console::LightReverse},
    // greenwoodbit
    {48, 3, 53, 10, console::LightTailReverse}, {56, 3, 90, 10, console::LightTailReverse}, {95, 3, 104, 10, console::LightTailReverse}, {112, 5, 127, 15, console::LightHead},
    // hermesbody64detail_ca
    {33, 31, 47, 47, console::LightHead}, {32, 32, 32, 47, console::LightHead}, {32, 48, 32, 48, console::LightBrake}, {33, 48, 63, 63, console::LightTailReverse},
    {32, 49, 32, 62, console::LightTailReverse}, {32, 63, 32, 63, console::LightBrake},
    // iz_idaho_interior
    {97, 72, 112, 77, console::LightTailReverse}, {113, 72, 126, 77, console::LightReverse}, {112, 96, 127, 101, console::LightHead}, {112, 102, 124, 127, console::LightHead},
    {126, 102, 127, 127, console::LightHead}, {125, 105, 125, 117, console::LightHead}, {125, 122, 125, 127, console::LightHead},
    // iz_landstalker_interior
    {65, 80, 78, 94, console::LightHead}, {66, 97, 77, 118, console::LightTailReverse}, {66, 119, 67, 124, console::LightTailReverse}, {68, 119, 75, 123, console::LightReverse},
    {76, 119, 77, 124, console::LightTailReverse}, {68, 124, 75, 124, console::LightTailReverse},
    // iz_manana_interior
    {112, 97, 125, 109, console::LightTailReverse}, {96, 112, 111, 117, console::LightHead}, {96, 118, 108, 120, console::LightHead}, {110, 118, 111, 127, console::LightHead},
    {96, 121, 107, 127, console::LightHead}, {109, 122, 109, 122, console::LightHead}, {108, 123, 108, 127, console::LightHead}, {109, 125, 109, 127, console::LightHead},
    // vcs_mopedbit
    {10, 63, 12, 69, console::LightHead}, {8, 64, 9, 71, console::LightHead}, {13, 64, 15, 71, console::LightHead}, {6, 65, 7, 72, console::LightHead},
    {16, 65, 16, 69, console::LightHead}, {5, 66, 5, 71, console::LightHead}, {17, 66, 17, 77, console::LightHead}, {18, 67, 18, 75, console::LightHead},
    {4, 68, 4, 75, console::LightHead}, {19, 68, 19, 68, console::LightReverse}, {19, 69, 19, 73, console::LightHead}, {3, 70, 3, 72, console::LightHead},
    {10, 70, 10, 71, console::LightHead}, {16, 71, 16, 77, console::LightHead}, {8, 72, 8, 72, console::LightHead}, {12, 72, 13, 79, console::LightHead},
    {15, 72, 15, 78, console::LightHead}, {5, 73, 5, 76, console::LightHead}, {7, 73, 7, 73, console::LightHead}, {10, 73, 11, 73, console::LightHead},
    {14, 73, 14, 78, console::LightHead}, {3, 74, 3, 74, console::LightReverse}, {11, 74, 11, 74, console::LightHead}, {19, 74, 19, 74, console::LightReverse},
    {6, 75, 6, 77, console::LightHead}, {4, 76, 4, 76, console::LightReverse}, {18, 76, 18, 76, console::LightReverse}, {5, 77, 5, 77, console::LightReverse},
    {7, 77, 8, 78, console::LightHead}, {6, 78, 6, 78, console::LightReverse}, {9, 78, 11, 79, console::LightHead}, {16, 78, 16, 78, console::LightReverse},
    {8, 79, 8, 79, console::LightReverse}, {14, 79, 15, 79, console::LightReverse}, {35, 102, 40, 105, console::LightReverse}, {33, 103, 34, 107, console::LightReverse},
    {41, 103, 42, 106, console::LightReverse}, {32, 104, 32, 108, console::LightReverse}, {43, 104, 43, 107, console::LightReverse}, {31, 105, 31, 108, console::LightReverse},
    {44, 105, 44, 108, console::LightReverse}, {30, 106, 30, 110, console::LightReverse}, {35, 106, 38, 106, console::LightReverse}, {39, 106, 39, 118, console::LightTailReverse},
    {40, 106, 40, 107, console::LightReverse}, {45, 106, 45, 115, console::LightReverse}, {35, 107, 38, 118, console::LightTailReverse}, {41, 107, 41, 117, console::LightTailReverse},
    {42, 107, 42, 107, console::LightReverse}, {29, 108, 29, 112, console::LightReverse}, {33, 108, 34, 117, console::LightTailReverse}, {40, 108, 40, 118, console::LightTailReverse},
    {42, 108, 43, 116, console::LightTailReverse}, {46, 108, 46, 112, console::LightReverse}, {31, 109, 32, 115, console::LightTailReverse}, {44, 109, 44, 115, console::LightTailReverse},
    {30, 111, 30, 112, console::LightTailReverse}, {30, 113, 30, 115, console::LightReverse}, {31, 116, 31, 116, console::LightReverse}, {32, 116, 32, 116, console::LightTailReverse},
    {44, 116, 44, 116, console::LightReverse}, {32, 117, 32, 117, console::LightReverse}, {42, 117, 42, 117, console::LightTailReverse}, {43, 117, 43, 117, console::LightReverse},
    {34, 118, 34, 118, console::LightTailReverse}, {41, 118, 41, 118, console::LightReverse},
    // vcs_oceanicbit
    {95, 0, 111, 10, console::LightHead}, {112, 0, 127, 14, console::LightTailReverse}, {96, 11, 111, 15, console::LightHead}, {95, 12, 95, 12, console::LightHead},
    {95, 14, 95, 15, console::LightHead}, {112, 15, 119, 15, console::LightTailReverse}, {120, 15, 120, 15, console::LightBrake}, {121, 15, 122, 15, console::LightTailReverse},
    {123, 15, 123, 15, console::LightBrake}, {124, 15, 125, 15, console::LightReverse}, {126, 15, 126, 15, console::LightBrake}, {127, 15, 127, 15, console::LightTailReverse},
    // sanchez8bit128
    {95, 96, 95, 97, console::LightReverse}, {96, 96, 127, 111, console::LightTailReverse}, {95, 99, 95, 101, console::LightReverse}, {95, 103, 95, 111, console::LightReverse},
    {96, 112, 110, 127, console::LightHead}, {111, 112, 127, 114, console::LightTailReverse}, {111, 115, 111, 115, console::LightHead}, {112, 115, 127, 127, console::LightTailReverse},
    {111, 116, 111, 117, console::LightTailReverse}, {111, 118, 111, 121, console::LightHead}, {111, 122, 111, 123, console::LightTailReverse}, {111, 124, 111, 126, console::LightHead},
    {111, 127, 111, 127, console::LightTailReverse},
    // stallion868bit128
    {32, 0, 40, 0, console::LightTailReverse}, {32, 1, 39, 6, console::LightTailReverse}, {40, 1, 40, 1, console::LightBrake}, {40, 2, 40, 2, console::LightTailReverse},
    {40, 3, 40, 3, console::LightBrake}, {40, 4, 40, 6, console::LightReverse}, {33, 13, 33, 13, console::LightReverse}, {34, 13, 37, 20, console::LightHead},
    {38, 13, 38, 13, console::LightReverse}, {32, 14, 32, 14, console::LightReverse}, {33, 14, 33, 19, console::LightHead}, {38, 14, 38, 19, console::LightHead},
    {39, 14, 39, 14, console::LightReverse}, {32, 15, 32, 18, console::LightHead}, {39, 15, 39, 18, console::LightHead}, {32, 19, 32, 19, console::LightReverse},
    {39, 19, 39, 19, console::LightReverse}, {33, 20, 33, 20, console::LightReverse}, {38, 20, 38, 20, console::LightReverse},
    // policebits
    {72, 15, 78, 21, console::LightReverse}, {81, 15, 81, 15, console::LightBrake}, {85, 15, 86, 15, console::LightBrake}, {89, 15, 90, 27, console::LightTailReverse},
    {91, 15, 91, 15, console::LightBrake}, {93, 15, 94, 27, console::LightTailReverse}, {95, 15, 95, 15, console::LightBrake}, {99, 15, 100, 20, console::LightTailReverse},
    {63, 16, 70, 20, console::LightTailReverse}, {71, 16, 71, 20, console::LightReverse}, {79, 16, 79, 20, console::LightReverse}, {81, 16, 88, 20, console::LightTailReverse},
    {91, 16, 92, 27, console::LightTailReverse}, {95, 16, 98, 20, console::LightTailReverse}, {101, 16, 107, 16, console::LightTailReverse}, {101, 17, 106, 20, console::LightTailReverse},
    {107, 17, 107, 17, console::LightBrake}, {64, 21, 64, 27, console::LightTailReverse}, {65, 21, 66, 21, console::LightBrake}, {67, 21, 68, 27, console::LightTailReverse},
    {69, 21, 69, 21, console::LightBrake}, {83, 21, 84, 21, console::LightTailReverse}, {85, 21, 88, 22, console::LightBrake}, {95, 21, 96, 27, console::LightTailReverse},
    {97, 21, 100, 22, console::LightBrake}, {105, 21, 105, 21, console::LightBrake}, {63, 22, 63, 22, console::LightBrake}, {65, 22, 66, 27, console::LightTailReverse},
    {69, 22, 69, 27, console::LightTailReverse}, {72, 22, 72, 27, console::LightTailReverse}, {73, 22, 74, 22, console::LightBrake}, {75, 22, 78, 27, console::LightTailReverse},
    {81, 22, 82, 27, console::LightTailReverse}, {83, 22, 84, 22, console::LightBrake}, {101, 22, 106, 27, console::LightTailReverse}, {63, 23, 63, 27, console::LightTailReverse},
    {70, 23, 70, 27, console::LightTailReverse}, {71, 23, 71, 23, console::LightBrake}, {73, 23, 74, 27, console::LightTailReverse}, {79, 23, 79, 27, console::LightTailReverse},
    {80, 23, 80, 23, console::LightBrake}, {83, 23, 88, 27, console::LightTailReverse}, {97, 23, 100, 27, console::LightTailReverse}, {80, 24, 80, 26, console::LightTailReverse},
    {80, 27, 80, 27, console::LightBrake}, {69, 28, 69, 28, console::LightBrake}, {82, 28, 92, 28, console::LightBrake}, {62, 31, 68, 43, console::LightHead},
    {74, 31, 80, 43, console::LightHead}, {69, 32, 70, 43, console::LightHead}, {73, 32, 73, 43, console::LightHead}, {81, 32, 81, 43, console::LightHead},
    {82, 33, 82, 43, console::LightHead}, {71, 34, 72, 43, console::LightHead},
    // patriotbit
    {29, 65, 44, 72, console::LightHead}, {77, 65, 77, 65, console::LightReverse}, {78, 65, 80, 65, console::LightBrake}, {81, 65, 89, 80, console::LightTailReverse},
    {90, 65, 90, 65, console::LightBrake}, {91, 65, 92, 65, console::LightReverse}, {77, 66, 77, 66, console::LightBrake}, {78, 66, 80, 79, console::LightTailReverse},
    {90, 66, 91, 80, console::LightTailReverse}, {92, 66, 92, 66, console::LightReverse}, {77, 67, 77, 67, console::LightReverse}, {92, 67, 92, 80, console::LightTailReverse},
    {77, 68, 77, 78, console::LightTailReverse}, {29, 73, 37, 80, console::LightHead}, {39, 73, 44, 73, console::LightHead}, {40, 74, 44, 80, console::LightHead},
    {38, 75, 39, 80, console::LightHead}, {77, 79, 77, 79, console::LightBrake}, {77, 80, 77, 80, console::LightReverse}, {78, 80, 78, 80, console::LightBrake},
    {79, 80, 80, 80, console::LightTailReverse},
    // ponybits_ca
    {120, 65, 125, 80, console::LightTailReverse}, {96, 80, 111, 85, console::LightHead}, {120, 81, 125, 85, console::LightReverse}, {96, 86, 101, 95, console::LightHead},
    {104, 86, 111, 95, console::LightHead}, {120, 86, 120, 94, console::LightReverse}, {123, 86, 125, 94, console::LightReverse}, {102, 87, 103, 95, console::LightHead},
    {122, 87, 122, 94, console::LightReverse}, {121, 88, 121, 94, console::LightReverse},
    // iz_sentinel86_interior
    {18, 66, 29, 77, console::LightHead}, {18, 82, 29, 93, console::LightHead}, {0, 96, 3, 96, console::LightBrake}, {4, 96, 7, 96, console::LightReverse},
    {8, 96, 9, 96, console::LightBrake}, {10, 96, 10, 111, console::LightTailReverse}, {11, 96, 11, 96, console::LightReverse}, {12, 96, 12, 96, console::LightBrake},
    {13, 96, 16, 111, console::LightTailReverse}, {17, 96, 20, 96, console::LightReverse}, {21, 96, 23, 109, console::LightTailReverse}, {24, 96, 25, 96, console::LightReverse},
    {26, 96, 26, 96, console::LightBrake}, {27, 96, 27, 96, console::LightReverse}, {28, 96, 28, 96, console::LightBrake}, {29, 96, 29, 111, console::LightTailReverse},
    {30, 96, 39, 96, console::LightReverse}, {40, 96, 41, 96, console::LightBrake}, {42, 96, 47, 96, console::LightReverse}, {0, 97, 9, 101, console::LightTailReverse},
    {11, 97, 12, 111, console::LightTailReverse}, {17, 97, 20, 109, console::LightTailReverse}, {24, 97, 28, 111, console::LightTailReverse}, {30, 97, 47, 99, console::LightTailReverse},
    {30, 100, 46, 107, console::LightTailReverse}, {47, 100, 47, 100, console::LightReverse}, {47, 101, 47, 107, console::LightTailReverse}, {0, 102, 1, 102, console::LightReverse},
    {2, 102, 9, 109, console::LightTailReverse}, {0, 103, 1, 103, console::LightTailReverse}, {0, 104, 1, 104, console::LightReverse}, {0, 105, 1, 105, console::LightTailReverse},
    {0, 106, 1, 106, console::LightReverse}, {0, 107, 1, 107, console::LightTailReverse}, {0, 108, 1, 108, console::LightReverse}, {30, 108, 33, 111, console::LightTailReverse},
    {34, 108, 35, 108, console::LightReverse}, {36, 108, 46, 109, console::LightTailReverse}, {47, 108, 47, 108, console::LightReverse}, {0, 109, 1, 109, console::LightTailReverse},
    {34, 109, 35, 109, console::LightTailReverse}, {47, 109, 47, 109, console::LightTailReverse}, {0, 110, 2, 110, console::LightReverse}, {3, 110, 4, 110, console::LightBrake},
    {5, 110, 6, 110, console::LightReverse}, {7, 110, 7, 110, console::LightBrake}, {8, 110, 9, 111, console::LightTailReverse}, {17, 110, 19, 111, console::LightTailReverse},
    {20, 110, 21, 110, console::LightBrake}, {22, 110, 23, 111, console::LightTailReverse}, {34, 110, 35, 110, console::LightReverse}, {36, 110, 39, 111, console::LightTailReverse},
    {40, 110, 41, 110, console::LightReverse}, {42, 110, 45, 111, console::LightTailReverse}, {46, 110, 47, 111, console::LightReverse}, {0, 111, 1, 111, console::LightReverse},
    {2, 111, 7, 111, console::LightTailReverse}, {20, 111, 21, 111, console::LightTailReverse}, {34, 111, 35, 111, console::LightTailReverse}, {40, 111, 41, 111, console::LightTailReverse},
    // pcj6008bit128
    {96, 96, 127, 111, console::LightTailReverse}, {96, 112, 127, 125, console::LightHead}, {97, 126, 127, 126, console::LightHead}, {98, 127, 127, 127, console::LightHead},
    // linerun_lights
    {0, 0, 0, 7, console::LightTailReverse}, {1, 0, 1, 0, console::LightReverse}, {2, 0, 2, 14, console::LightTailReverse}, {3, 0, 3, 0, console::LightReverse},
    {4, 0, 4, 14, console::LightTailReverse}, {5, 0, 5, 0, console::LightReverse}, {6, 0, 8, 13, console::LightTailReverse}, {9, 0, 9, 0, console::LightReverse},
    {10, 0, 13, 12, console::LightTailReverse}, {14, 0, 15, 0, console::LightReverse}, {1, 1, 1, 14, console::LightTailReverse}, {3, 1, 3, 11, console::LightTailReverse},
    {5, 1, 5, 13, console::LightTailReverse}, {9, 1, 9, 13, console::LightTailReverse}, {14, 1, 15, 1, console::LightTailReverse}, {14, 2, 14, 14, console::LightTailReverse},
    {15, 2, 15, 4, console::LightReverse}, {15, 5, 15, 12, console::LightTailReverse}, {0, 8, 0, 10, console::LightReverse}, {0, 11, 0, 11, console::LightTailReverse},
    {0, 12, 0, 15, console::LightReverse}, {3, 12, 3, 12, console::LightReverse}, {3, 13, 3, 14, console::LightTailReverse}, {10, 13, 10, 13, console::LightTailReverse},
    {11, 13, 11, 15, console::LightReverse}, {12, 13, 13, 13, console::LightTailReverse}, {15, 13, 15, 15, console::LightReverse}, {5, 14, 5, 15, console::LightReverse},
    {6, 14, 6, 14, console::LightTailReverse}, {7, 14, 10, 15, console::LightReverse}, {12, 14, 13, 15, console::LightReverse}, {1, 15, 4, 15, console::LightReverse},
    {6, 15, 6, 15, console::LightReverse}, {14, 15, 14, 15, console::LightReverse}, {0, 16, 31, 31, console::LightHead},
    // waltonbit
    {4, 97, 4, 97, console::LightReverse}, {5, 97, 10, 110, console::LightHead}, {11, 97, 11, 97, console::LightReverse}, {3, 98, 3, 98, console::LightReverse},
    {4, 98, 4, 109, console::LightHead}, {11, 98, 11, 109, console::LightHead}, {12, 98, 12, 98, console::LightReverse}, {2, 99, 2, 99, console::LightReverse},
    {3, 99, 3, 108, console::LightHead}, {12, 99, 12, 108, console::LightHead}, {13, 99, 13, 99, console::LightReverse}, {1, 100, 1, 100, console::LightReverse},
    {2, 100, 2, 107, console::LightHead}, {14, 100, 14, 100, console::LightReverse}, {1, 101, 1, 106, console::LightHead}, {14, 101, 14, 106, console::LightHead},
    {13, 103, 13, 107, console::LightHead}, {1, 107, 1, 107, console::LightReverse}, {14, 107, 14, 107, console::LightReverse}, {2, 108, 2, 108, console::LightReverse},
    {13, 108, 13, 108, console::LightReverse}, {3, 109, 3, 109, console::LightReverse}, {12, 109, 12, 109, console::LightReverse}, {4, 110, 4, 110, console::LightReverse},
    {11, 110, 11, 110, console::LightReverse}, {5, 111, 10, 111, console::LightBrake}, {3, 112, 4, 112, console::LightBrake}, {5, 112, 10, 127, console::LightTailReverse},
    {11, 112, 12, 112, console::LightBrake}, {2, 113, 2, 113, console::LightBrake}, {3, 113, 4, 126, console::LightTailReverse}, {11, 113, 12, 126, console::LightTailReverse},
    {13, 113, 13, 113, console::LightBrake}, {1, 114, 1, 114, console::LightBrake}, {2, 114, 2, 125, console::LightTailReverse}, {13, 114, 13, 125, console::LightTailReverse},
    {14, 114, 14, 114, console::LightBrake}, {1, 115, 1, 124, console::LightTailReverse}, {14, 115, 14, 124, console::LightTailReverse}, {0, 116, 0, 116, console::LightBrake},
    {15, 116, 15, 116, console::LightBrake}, {0, 117, 0, 122, console::LightTailReverse}, {15, 117, 15, 122, console::LightTailReverse}, {4, 127, 4, 127, console::LightReverse},
    {11, 127, 11, 127, console::LightReverse},
    // barracksbits
    {65, 32, 80, 44, console::LightTailReverse}, {65, 45, 65, 46, console::LightTailReverse}, {66, 45, 66, 47, console::LightReverse}, {67, 45, 67, 45, console::LightBrake},
    {68, 45, 80, 45, console::LightTailReverse}, {67, 46, 70, 46, console::LightTailReverse}, {71, 46, 71, 46, console::LightReverse}, {72, 46, 72, 46, console::LightBrake},
    {73, 46, 73, 46, console::LightTailReverse}, {74, 46, 74, 46, console::LightReverse}, {80, 46, 80, 46, console::LightTailReverse}, {65, 47, 65, 47, console::LightBrake},
    {67, 47, 70, 47, console::LightReverse}, {80, 47, 80, 47, console::LightReverse}, {81, 48, 96, 55, console::LightHead}, {81, 56, 93, 56, console::LightHead},
    {95, 56, 96, 63, console::LightHead}, {81, 57, 92, 63, console::LightHead}, {94, 57, 94, 58, console::LightHead}, {93, 59, 93, 63, console::LightHead},
    {94, 60, 94, 63, console::LightHead},
    // flatbed868bit128
    {64, 32, 79, 45, console::LightTailReverse}, {64, 46, 72, 46, console::LightTailReverse}, {76, 46, 76, 46, console::LightBrake}, {77, 46, 79, 46, console::LightTailReverse},
    {64, 47, 67, 47, console::LightBrake}, {81, 49, 94, 62, console::LightHead}, {97, 81, 111, 94, console::LightReverse},
    // armytruk8bit128
    {64, 32, 77, 40, console::LightTailReverse}, {78, 32, 79, 32, console::LightBrake}, {78, 33, 79, 45, console::LightTailReverse}, {64, 41, 64, 43, console::LightBrake},
    {65, 41, 77, 45, console::LightTailReverse}, {64, 44, 64, 46, console::LightTailReverse}, {65, 46, 69, 46, console::LightTailReverse}, {70, 46, 72, 46, console::LightBrake},
    {77, 46, 78, 46, console::LightTailReverse}, {79, 46, 79, 46, console::LightBrake}, {80, 48, 95, 62, console::LightHead}, {80, 63, 87, 63, console::LightHead},
    {96, 80, 111, 94, console::LightReverse}, {96, 95, 103, 95, console::LightReverse},
    // iz_moonbeam_interior
    {96, 64, 112, 65, console::LightTailReverse}, {113, 64, 115, 65, console::LightReverse}, {116, 64, 126, 65, console::LightTailReverse}, {96, 66, 101, 66, console::LightTailReverse},
    {111, 66, 115, 67, console::LightTailReverse}, {122, 66, 126, 66, console::LightTailReverse}, {96, 67, 100, 75, console::LightTailReverse}, {104, 67, 110, 75, console::LightTailReverse},
    {116, 67, 120, 75, console::LightTailReverse}, {123, 67, 126, 78, console::LightTailReverse}, {102, 68, 103, 74, console::LightTailReverse}, {111, 68, 112, 75, console::LightTailReverse},
    {113, 68, 114, 72, console::LightReverse}, {115, 68, 115, 75, console::LightTailReverse}, {122, 68, 122, 78, console::LightTailReverse}, {101, 69, 101, 74, console::LightTailReverse},
    {113, 73, 113, 74, console::LightReverse}, {114, 73, 114, 75, console::LightTailReverse}, {103, 75, 103, 75, console::LightTailReverse}, {113, 75, 113, 75, console::LightTailReverse},
    {96, 76, 99, 76, console::LightTailReverse}, {96, 77, 96, 78, console::LightReverse}, {97, 77, 100, 78, console::LightTailReverse}, {104, 77, 115, 77, console::LightTailReverse},
    {116, 77, 116, 77, console::LightBrake}, {117, 77, 119, 78, console::LightReverse}, {120, 77, 121, 77, console::LightTailReverse}, {101, 78, 114, 78, console::LightTailReverse},
    {115, 78, 116, 78, console::LightReverse}, {121, 78, 121, 78, console::LightTailReverse}, {96, 80, 111, 95, console::LightHead}, {112, 80, 127, 95, console::LightReverse},
    // rumpobits_ca
    {60, 32, 60, 40, console::LightTailReverse}, {61, 32, 62, 32, console::LightBrake}, {61, 33, 62, 39, console::LightTailReverse}, {48, 40, 55, 47, console::LightHead},
    {61, 40, 61, 40, console::LightTailReverse}, {62, 40, 62, 47, console::LightReverse}, {60, 41, 61, 47, console::LightReverse},
    // miami_cabbietex128
    {72, 15, 78, 21, console::LightReverse}, {89, 15, 90, 15, console::LightBrake}, {93, 15, 94, 15, console::LightBrake}, {63, 16, 70, 20, console::LightTailReverse},
    {71, 16, 71, 20, console::LightReverse}, {79, 16, 79, 20, console::LightReverse}, {81, 16, 106, 20, console::LightTailReverse}, {107, 16, 107, 16, console::LightBrake},
    {64, 21, 64, 27, console::LightTailReverse}, {65, 21, 66, 21, console::LightBrake}, {67, 21, 68, 27, console::LightTailReverse}, {69, 21, 69, 21, console::LightBrake},
    {83, 21, 84, 21, console::LightTailReverse}, {85, 21, 88, 22, console::LightBrake}, {89, 21, 96, 27, console::LightTailReverse}, {97, 21, 100, 22, console::LightBrake},
    {105, 21, 105, 21, console::LightBrake}, {63, 22, 63, 22, console::LightBrake}, {65, 22, 66, 27, console::LightTailReverse}, {69, 22, 69, 27, console::LightTailReverse},
    {72, 22, 72, 27, console::LightTailReverse}, {73, 22, 74, 22, console::LightBrake}, {75, 22, 78, 27, console::LightTailReverse}, {81, 22, 82, 27, console::LightTailReverse},
    {83, 22, 84, 22, console::LightBrake}, {101, 22, 106, 27, console::LightTailReverse}, {63, 23, 63, 27, console::LightTailReverse}, {70, 23, 70, 27, console::LightTailReverse},
    {71, 23, 71, 23, console::LightBrake}, {73, 23, 74, 27, console::LightTailReverse}, {79, 23, 79, 27, console::LightTailReverse}, {80, 23, 80, 23, console::LightBrake},
    {83, 23, 88, 27, console::LightTailReverse}, {97, 23, 100, 27, console::LightTailReverse}, {80, 24, 80, 26, console::LightTailReverse}, {80, 27, 80, 27, console::LightBrake},
    {69, 28, 69, 28, console::LightBrake}, {82, 28, 92, 28, console::LightBrake}, {62, 31, 68, 43, console::LightHead}, {74, 31, 74, 43, console::LightHead},
    {77, 31, 80, 43, console::LightHead}, {73, 32, 73, 43, console::LightHead}, {75, 32, 76, 43, console::LightHead}, {81, 32, 81, 43, console::LightHead},
    {69, 33, 70, 43, console::LightHead}, {82, 34, 82, 43, console::LightHead}, {71, 35, 71, 40, console::LightHead}, {72, 36, 72, 42, console::LightHead},
    // ambulan8bit128
    {97, 0, 110, 6, console::LightHead}, {96, 1, 96, 9, console::LightHead}, {111, 1, 111, 1, console::LightHead}, {97, 7, 97, 7, console::LightHead},
    {99, 7, 111, 7, console::LightHead}, {99, 8, 108, 9, console::LightHead}, {111, 8, 111, 9, console::LightHead}, {100, 10, 107, 10, console::LightHead},
    {101, 11, 107, 12, console::LightHead}, {102, 13, 106, 13, console::LightHead}, {113, 32, 126, 41, console::LightHead}, {120, 45, 122, 46, console::LightHead},
    {123, 46, 124, 47, console::LightHead}, {119, 47, 119, 49, console::LightHead}, {122, 47, 122, 48, console::LightHead}, {120, 49, 120, 49, console::LightHead},
    {114, 53, 126, 62, console::LightHead}, {113, 54, 113, 62, console::LightHead}, {123, 63, 126, 63, console::LightHead}, {82, 68, 92, 79, console::LightHead},
    {81, 69, 81, 69, console::LightHead}, {93, 69, 93, 79, console::LightHead}, {95, 96, 111, 107, console::LightHead}, {112, 96, 127, 110, console::LightTailReverse},
    {96, 108, 111, 115, console::LightHead}, {112, 111, 112, 111, console::LightTailReverse}, {113, 111, 113, 111, console::LightReverse}, {114, 111, 115, 111, console::LightBrake},
    {116, 111, 118, 111, console::LightTailReverse}, {119, 111, 119, 111, console::LightReverse}, {120, 111, 120, 111, console::LightTailReverse}, {121, 111, 121, 111, console::LightBrake},
    {122, 111, 122, 111, console::LightReverse}, {123, 111, 124, 111, console::LightTailReverse}, {125, 111, 125, 111, console::LightReverse}, {126, 111, 127, 111, console::LightTailReverse},
    {112, 112, 127, 115, console::LightHead}, {96, 116, 103, 126, console::LightHead}, {108, 116, 115, 119, console::LightHead}, {120, 116, 127, 120, console::LightHead},
    {116, 117, 117, 119, console::LightHead}, {104, 118, 107, 119, console::LightHead}, {118, 119, 118, 120, console::LightHead}, {106, 120, 107, 120, console::LightHead},
    {109, 120, 115, 121, console::LightHead}, {117, 120, 117, 121, console::LightHead}, {121, 121, 127, 126, console::LightHead}, {106, 122, 114, 123, console::LightHead},
    {118, 122, 120, 123, console::LightHead}, {115, 123, 115, 127, console::LightHead}, {106, 124, 106, 124, console::LightHead}, {108, 124, 114, 126, console::LightHead},
    {120, 124, 120, 126, console::LightHead}, {97, 127, 103, 127, console::LightHead}, {109, 127, 114, 127, console::LightHead}, {121, 127, 126, 127, console::LightHead},
    // stretchbit
    {82, 2, 109, 5, console::LightHead}, {82, 6, 91, 13, console::LightHead}, {93, 6, 93, 7, console::LightHead}, {95, 6, 109, 13, console::LightHead},
    {92, 7, 92, 13, console::LightHead}, {94, 7, 94, 13, console::LightHead}, {93, 9, 93, 13, console::LightHead}, {113, 17, 126, 46, console::LightTailReverse},
    // faggio8bit128
    {98, 34, 110, 46, console::LightHead}, {112, 80, 113, 80, console::LightReverse}, {114, 80, 125, 95, console::LightTailReverse}, {126, 80, 126, 80, console::LightBrake},
    {112, 81, 113, 94, console::LightTailReverse}, {126, 81, 127, 94, console::LightTailReverse}, {112, 95, 113, 95, console::LightReverse}, {126, 95, 126, 95, console::LightBrake},
    // vcs_quadbitv3_sjl
    {67, 31, 73, 42, console::LightTailReverse}, {63, 32, 66, 42, console::LightTailReverse}, {74, 32, 77, 41, console::LightTailReverse}, {62, 33, 62, 41, console::LightTailReverse},
    {74, 42, 76, 42, console::LightTailReverse}, {10, 68, 15, 83, console::LightHead}, {8, 69, 9, 82, console::LightHead}, {16, 69, 17, 82, console::LightHead},
    {7, 70, 7, 82, console::LightHead}, {18, 70, 18, 82, console::LightHead}, {6, 71, 6, 81, console::LightHead}, {19, 71, 19, 81, console::LightHead},
    {5, 72, 5, 80, console::LightHead}, {20, 72, 20, 80, console::LightHead}, {4, 75, 4, 78, console::LightHead}, {21, 78, 21, 78, console::LightHead},
    {9, 83, 9, 83, console::LightHead}, {16, 83, 16, 83, console::LightHead}, {5, 90, 19, 105, console::LightHead}, {20, 91, 20, 104, console::LightHead},
    {4, 95, 4, 103, console::LightHead},
    // angel8bit128
    {96, 96, 111, 111, console::LightHead}, {96, 112, 96, 112, console::LightReverse}, {100, 112, 102, 112, console::LightReverse}, {103, 112, 103, 112, console::LightBrake},
    {104, 112, 116, 126, console::LightTailReverse}, {117, 112, 117, 112, console::LightBrake}, {118, 112, 123, 112, console::LightReverse}, {126, 112, 126, 112, console::LightReverse},
    {97, 113, 103, 126, console::LightTailReverse}, {117, 113, 127, 125, console::LightTailReverse}, {96, 114, 96, 114, console::LightReverse}, {96, 115, 96, 121, console::LightTailReverse},
    {96, 122, 96, 122, console::LightBrake}, {96, 123, 96, 124, console::LightReverse}, {117, 126, 126, 126, console::LightTailReverse}, {127, 126, 127, 126, console::LightBrake},
    {97, 127, 99, 127, console::LightReverse}, {100, 127, 101, 127, console::LightBrake}, {102, 127, 112, 127, console::LightTailReverse}, {113, 127, 113, 127, console::LightBrake},
    {114, 127, 114, 127, console::LightTailReverse}, {115, 127, 116, 127, console::LightBrake}, {117, 127, 123, 127, console::LightReverse}, {124, 127, 125, 127, console::LightBrake},
    // enforcer868bit128
    {112, 80, 127, 94, console::LightReverse}, {112, 95, 119, 95, console::LightReverse}, {96, 96, 104, 110, console::LightTailReverse}, {105, 96, 105, 97, console::LightBrake},
    {106, 96, 111, 110, console::LightTailReverse}, {105, 98, 105, 110, console::LightTailReverse}, {97, 111, 103, 111, console::LightTailReverse}, {110, 111, 110, 111, console::LightBrake},
    {112, 112, 127, 127, console::LightHead},
    // boxville868bit128
    {32, 65, 33, 65, console::LightBrake}, {34, 65, 34, 65, console::LightReverse}, {35, 65, 35, 65, console::LightBrake}, {36, 65, 40, 95, console::LightTailReverse},
    {41, 65, 46, 65, console::LightBrake}, {47, 65, 47, 67, console::LightReverse}, {32, 66, 32, 67, console::LightBrake}, {33, 66, 35, 95, console::LightTailReverse},
    {41, 66, 46, 95, console::LightTailReverse}, {32, 68, 32, 95, console::LightTailReverse}, {47, 68, 47, 70, console::LightBrake}, {47, 71, 47, 73, console::LightTailReverse},
    {111, 72, 127, 86, console::LightHead}, {47, 74, 47, 94, console::LightBrake}, {111, 87, 114, 87, console::LightHead}, {127, 87, 127, 87, console::LightHead},
    {47, 95, 47, 95, console::LightReverse}, {32, 96, 35, 96, console::LightReverse}, {36, 96, 38, 96, console::LightBrake}, {39, 96, 40, 96, console::LightReverse},
    // benson_bits
    {5, 49, 10, 61, console::LightHead}, {4, 50, 4, 61, console::LightHead}, {11, 50, 11, 61, console::LightHead}, {3, 51, 3, 60, console::LightHead},
    {12, 51, 12, 60, console::LightHead}, {2, 52, 2, 59, console::LightHead}, {13, 52, 13, 59, console::LightHead}, {1, 54, 1, 57, console::LightHead},
    {14, 54, 14, 57, console::LightHead}, {6, 62, 10, 62, console::LightHead}, {71, 80, 71, 80, console::LightReverse}, {72, 80, 85, 89, console::LightTailReverse},
    {86, 80, 86, 80, console::LightReverse}, {71, 81, 71, 83, console::LightBrake}, {86, 81, 86, 85, console::LightBrake}, {71, 84, 71, 94, console::LightTailReverse},
    {86, 86, 86, 95, console::LightReverse}, {72, 90, 84, 95, console::LightTailReverse}, {85, 90, 85, 90, console::LightBrake}, {85, 91, 85, 94, console::LightTailReverse},
    {71, 95, 71, 95, console::LightReverse}, {85, 95, 85, 95, console::LightReverse},
    // coach868bit128
    {33, 65, 62, 78, console::LightHead}, {0, 96, 14, 111, console::LightTailReverse}, {15, 96, 15, 96, console::LightBrake}, {15, 97, 15, 111, console::LightTailReverse},
    {0, 112, 15, 127, console::LightReverse},
    // mule8bit128
    {72, 8, 88, 22, console::LightHead}, {80, 64, 96, 79, console::LightHead}, {112, 64, 126, 94, console::LightTailReverse}, {127, 65, 127, 65, console::LightBrake},
    {127, 66, 127, 94, console::LightTailReverse}, {112, 95, 112, 95, console::LightReverse}, {113, 95, 126, 95, console::LightTailReverse}, {127, 95, 127, 95, console::LightReverse},
    // voodoobit
    {101, 0, 114, 12, console::LightHead}, {115, 0, 127, 11, console::LightTailReverse}, {115, 12, 121, 12, console::LightTailReverse}, {122, 12, 123, 12, console::LightReverse},
    {126, 12, 127, 12, console::LightTailReverse},
    // securica868bit128
    {111, 64, 111, 72, console::LightReverse}, {112, 64, 114, 72, console::LightTailReverse}, {115, 64, 115, 64, console::LightBrake}, {116, 64, 126, 79, console::LightTailReverse},
    {127, 64, 127, 64, console::LightReverse}, {115, 65, 115, 79, console::LightTailReverse}, {127, 65, 127, 66, console::LightTailReverse}, {127, 67, 127, 67, console::LightReverse},
    {127, 68, 127, 79, console::LightTailReverse}, {112, 73, 112, 74, console::LightReverse}, {113, 73, 114, 79, console::LightTailReverse}, {111, 75, 111, 79, console::LightReverse},
    {112, 75, 112, 79, console::LightTailReverse}, {96, 80, 111, 94, console::LightHead}, {112, 80, 127, 94, console::LightReverse}, {96, 95, 103, 95, console::LightHead},
    {112, 95, 118, 95, console::LightReverse},
    // trash868bit128
    {96, 96, 111, 110, console::LightHead}, {112, 96, 125, 104, console::LightTailReverse}, {126, 96, 127, 96, console::LightBrake}, {126, 97, 127, 109, console::LightTailReverse},
    {112, 105, 112, 107, console::LightBrake}, {113, 105, 125, 109, console::LightTailReverse}, {112, 108, 112, 110, console::LightTailReverse}, {113, 110, 117, 110, console::LightTailReverse},
    {118, 110, 120, 110, console::LightBrake}, {121, 110, 124, 110, console::LightReverse}, {125, 110, 126, 110, console::LightTailReverse}, {127, 110, 127, 110, console::LightBrake},
    {96, 111, 103, 111, console::LightHead}, {112, 111, 117, 111, console::LightReverse},
    // yankee_bits
    {16, 64, 31, 77, console::LightTailReverse}, {32, 64, 47, 78, console::LightHead}, {16, 78, 23, 79, console::LightTailReverse}, {24, 78, 26, 79, console::LightReverse},
    {27, 78, 31, 78, console::LightTailReverse}, {27, 79, 27, 79, console::LightReverse}, {28, 79, 31, 79, console::LightTailReverse}, {32, 79, 43, 79, console::LightHead},
    {46, 79, 47, 79, console::LightHead}, {114, 99, 125, 107, console::LightTail}, {114, 108, 116, 124, console::LightTail}, {119, 108, 125, 124, console::LightTail},
    {118, 110, 118, 124, console::LightTail}, {117, 111, 117, 124, console::LightTail},
    // mrwhoo868bit128
    {32, 67, 46, 94, console::LightTailReverse}, {112, 71, 127, 72, console::LightHead}, {112, 73, 113, 86, console::LightHead}, {116, 73, 127, 86, console::LightHead},
    {114, 74, 115, 86, console::LightHead}, {32, 95, 44, 95, console::LightReverse},
    // sandkingbit
    {94, 37, 103, 55, console::LightTailReverse}, {94, 56, 94, 61, console::LightTailReverse}, {95, 56, 102, 60, console::LightReverse}, {103, 56, 103, 61, console::LightTailReverse},
    {95, 61, 102, 61, console::LightTailReverse}, {0, 96, 15, 101, console::LightHead}, {0, 102, 12, 127, console::LightHead}, {14, 102, 15, 127, console::LightHead},
    {13, 105, 13, 117, console::LightHead}, {13, 121, 13, 127, console::LightHead},
    // forkbit
    {11, 68, 14, 83, console::LightHead}, {9, 69, 10, 82, console::LightHead}, {15, 69, 17, 82, console::LightHead}, {8, 70, 8, 82, console::LightHead},
    {18, 70, 18, 81, console::LightHead}, {7, 71, 7, 81, console::LightHead}, {19, 71, 19, 80, console::LightHead}, {6, 72, 6, 80, console::LightHead},
    {20, 73, 20, 78, console::LightHead}, {5, 74, 5, 78, console::LightHead}, {20, 79, 20, 79, console::LightReverse}, {9, 83, 9, 83, console::LightReverse},
    {10, 83, 10, 83, console::LightHead}, {15, 83, 15, 83, console::LightHead}, {66, 88, 78, 95, console::LightHead}, {17, 91, 27, 99, console::LightTailReverse},
    {66, 96, 66, 96, console::LightHead}, {68, 96, 77, 96, console::LightHead},
    // vcs_streetfighterbit
    {14, 28, 26, 28, console::LightReverse}, {14, 29, 16, 29, console::LightTailReverse}, {17, 29, 17, 29, console::LightReverse}, {18, 29, 18, 30, console::LightTailReverse},
    {19, 29, 19, 29, console::LightReverse}, {20, 29, 26, 29, console::LightTailReverse}, {14, 30, 14, 30, console::LightReverse}, {15, 30, 15, 31, console::LightTailReverse},
    {16, 30, 16, 31, console::LightReverse}, {17, 30, 17, 31, console::LightTailReverse}, {19, 30, 19, 30, console::LightTailReverse}, {20, 30, 20, 30, console::LightReverse},
    {21, 30, 21, 30, console::LightTailReverse}, {22, 30, 22, 30, console::LightReverse}, {23, 30, 23, 31, console::LightTailReverse}, {24, 30, 24, 31, console::LightReverse},
    {25, 30, 25, 31, console::LightTailReverse}, {26, 30, 26, 33, console::LightReverse}, {43, 30, 45, 51, console::LightHead}, {14, 31, 14, 31, console::LightTailReverse},
    {18, 31, 19, 31, console::LightReverse}, {20, 31, 20, 31, console::LightTailReverse}, {21, 31, 21, 31, console::LightReverse}, {22, 31, 22, 31, console::LightTailReverse},
    {40, 31, 42, 55, console::LightHead}, {46, 31, 48, 46, console::LightHead}, {14, 32, 15, 32, console::LightReverse}, {16, 32, 16, 32, console::LightTailReverse},
    {17, 32, 17, 32, console::LightReverse}, {18, 32, 19, 32, console::LightTailReverse}, {20, 32, 20, 32, console::LightReverse}, {21, 32, 21, 32, console::LightTailReverse},
    {22, 32, 23, 32, console::LightReverse}, {24, 32, 24, 39, console::LightTailReverse}, {25, 32, 25, 32, console::LightReverse}, {37, 32, 37, 53, console::LightHead},
    {39, 32, 39, 47, console::LightHead}, {49, 32, 50, 44, console::LightHead}, {14, 33, 15, 39, console::LightTailReverse}, {16, 33, 16, 33, console::LightReverse},
    {17, 33, 17, 40, console::LightTailReverse}, {18, 33, 18, 33, console::LightReverse}, {19, 33, 20, 39, console::LightTailReverse}, {21, 33, 21, 33, console::LightReverse},
    {22, 33, 23, 39, console::LightTailReverse}, {25, 33, 25, 39, console::LightTailReverse}, {36, 33, 36, 46, console::LightHead}, {38, 33, 38, 54, console::LightHead},
    {51, 33, 51, 46, console::LightHead}, {16, 34, 16, 39, console::LightTailReverse}, {18, 34, 18, 39, console::LightTailReverse}, {21, 34, 21, 40, console::LightTailReverse},
    {26, 34, 26, 39, console::LightTailReverse}, {52, 34, 52, 52, console::LightHead}, {35, 35, 35, 52, console::LightHead}, {53, 35, 53, 51, console::LightHead},
    {34, 36, 34, 51, console::LightHead}, {54, 36, 54, 50, console::LightHead}, {33, 37, 33, 50, console::LightHead}, {55, 37, 55, 48, console::LightHead},
    {32, 38, 32, 48, console::LightHead}, {56, 39, 56, 45, console::LightHead}, {14, 40, 14, 40, console::LightReverse}, {15, 40, 15, 40, console::LightTailReverse},
    {16, 40, 16, 40, console::LightReverse}, {18, 40, 18, 40, console::LightReverse}, {19, 40, 19, 40, console::LightTailReverse}, {20, 40, 20, 40, console::LightReverse},
    {22, 40, 22, 40, console::LightReverse}, {23, 40, 23, 40, console::LightTailReverse}, {25, 40, 25, 40, console::LightReverse}, {31, 41, 31, 45, console::LightHead},
    {49, 45, 49, 45, console::LightHead}, {56, 46, 56, 47, console::LightReverse}, {46, 47, 46, 51, console::LightHead}, {50, 47, 50, 48, console::LightHead},
    {36, 48, 36, 53, console::LightHead}, {47, 48, 47, 50, console::LightHead}, {49, 48, 49, 48, console::LightHead}, {51, 48, 51, 53, console::LightHead},
    {32, 49, 32, 49, console::LightReverse}, {39, 49, 39, 54, console::LightHead}, {48, 49, 48, 49, console::LightHead}, {49, 50, 50, 53, console::LightHead},
    {48, 51, 48, 54, console::LightHead}, {43, 52, 44, 53, console::LightHead}, {47, 52, 47, 54, console::LightHead}, {45, 53, 46, 55, console::LightHead},
    {37, 54, 37, 54, console::LightReverse}, {43, 54, 43, 55, console::LightHead}, {49, 54, 49, 54, console::LightHead}, {44, 55, 44, 55, console::LightHead},
    {47, 55, 47, 55, console::LightReverse},
    // virgobit
    {44, 8, 54, 11, console::LightTailReverse}, {55, 9, 55, 9, console::LightTailReverse}, {55, 11, 55, 32, console::LightTailReverse}, {45, 12, 54, 13, console::LightTailReverse},
    {44, 13, 44, 32, console::LightTailReverse}, {45, 14, 45, 27, console::LightTailReverse}, {47, 14, 54, 17, console::LightTailReverse}, {46, 15, 46, 27, console::LightTailReverse},
    {47, 18, 47, 27, console::LightTailReverse}, {49, 18, 54, 27, console::LightTailReverse}, {48, 19, 48, 27, console::LightTailReverse}, {45, 28, 54, 32, console::LightReverse},
    {49, 37, 70, 37, console::LightTailReverse}, {72, 37, 87, 37, console::LightTailReverse}, {49, 38, 59, 39, console::LightTailReverse}, {61, 38, 70, 39, console::LightTailReverse},
    {72, 38, 83, 40, console::LightReverse}, {84, 38, 87, 39, console::LightTailReverse}, {60, 39, 60, 42, console::LightTailReverse}, {50, 40, 59, 42, console::LightTailReverse},
    {61, 40, 69, 41, console::LightTailReverse}, {84, 40, 85, 40, console::LightTailReverse}, {86, 40, 86, 40, console::LightBrake}, {87, 40, 87, 40, console::LightTailReverse},
    {49, 41, 49, 42, console::LightTailReverse}, {70, 41, 70, 42, console::LightTailReverse}, {72, 41, 83, 43, console::LightTailReverse}, {84, 41, 84, 41, console::LightBrake},
    {85, 41, 86, 41, console::LightTailReverse}, {87, 41, 87, 41, console::LightBrake}, {62, 42, 64, 42, console::LightTailReverse}, {66, 42, 69, 42, console::LightTailReverse},
    {84, 42, 84, 42, console::LightTailReverse}, {85, 42, 85, 43, console::LightBrake}, {86, 42, 87, 42, console::LightTailReverse}, {84, 43, 84, 43, console::LightBrake},
    {86, 43, 87, 43, console::LightBrake}, {45, 66, 51, 76, console::LightHead}, {60, 66, 66, 76, console::LightHead}, {44, 67, 44, 75, console::LightHead},
    {52, 67, 52, 68, console::LightHead}, {59, 67, 59, 75, console::LightHead}, {67, 67, 67, 75, console::LightHead}, {43, 68, 43, 74, console::LightHead},
    {53, 68, 53, 68, console::LightHead}, {58, 68, 58, 74, console::LightHead}, {68, 69, 68, 74, console::LightHead}, {52, 70, 53, 74, console::LightHead},
    {52, 75, 52, 75, console::LightHead},
    // stingerbit
    {0, 0, 15, 13, console::LightTailReverse}, {0, 14, 13, 15, console::LightTailReverse}, {14, 14, 14, 14, console::LightReverse}, {15, 14, 15, 15, console::LightTailReverse},
    {14, 15, 14, 15, console::LightTailReverse}, {0, 16, 31, 31, console::LightHead},
    // bfinject868bit128
    {22, 81, 25, 94, console::LightHead}, {20, 82, 21, 93, console::LightHead}, {26, 82, 27, 93, console::LightHead}, {19, 83, 19, 92, console::LightHead},
    {28, 83, 28, 92, console::LightHead}, {18, 84, 18, 91, console::LightHead}, {29, 84, 29, 91, console::LightHead}, {17, 86, 17, 89, console::LightHead},
    {30, 86, 30, 89, console::LightHead}, {16, 112, 31, 127, console::LightTailReverse},
    // pheonixbit
    {15, 0, 30, 14, console::LightHead}, {31, 1, 44, 7, console::LightTailReverse}, {45, 2, 45, 15, console::LightTailReverse}, {46, 5, 46, 10, console::LightTailReverse},
    {31, 8, 31, 16, console::LightReverse}, {32, 8, 44, 13, console::LightTailReverse}, {46, 12, 46, 13, console::LightTailReverse}, {32, 14, 39, 14, console::LightTailReverse},
    {40, 14, 40, 15, console::LightReverse}, {41, 14, 44, 14, console::LightTailReverse}, {15, 15, 29, 16, console::LightHead}, {32, 15, 35, 15, console::LightTailReverse},
    {41, 15, 43, 15, console::LightReverse}, {15, 17, 28, 30, console::LightHead}, {29, 18, 30, 31, console::LightHead}, {16, 31, 28, 31, console::LightHead},
    // mesabit
    {0, 96, 15, 111, console::LightHead}, {0, 112, 15, 127, console::LightTailReverse},
    // chollo_details1
    {0, 18, 13, 21, console::LightHead}, {14, 18, 30, 32, console::LightTailReverse}, {0, 22, 3, 32, console::LightHead}, {6, 22, 13, 32, console::LightHead},
    {4, 23, 5, 32, console::LightHead},
    // vcs_cometbit
    {48, 0, 63, 15, console::LightHead}, {32, 16, 43, 31, console::LightTailReverse}, {44, 16, 45, 16, console::LightBrake}, {46, 16, 46, 19, console::LightTailReverse},
    {47, 16, 47, 16, console::LightBrake}, {48, 16, 63, 19, console::LightTailReverse}, {44, 17, 45, 17, console::LightTailReverse}, {47, 17, 47, 17, console::LightTailReverse},
    {44, 18, 44, 31, console::LightTailReverse}, {45, 18, 45, 18, console::LightBrake}, {47, 18, 47, 18, console::LightBrake}, {45, 19, 45, 19, console::LightTailReverse},
    {47, 19, 47, 31, console::LightTailReverse}, {45, 20, 46, 20, console::LightBrake}, {48, 20, 60, 31, console::LightTailReverse}, {61, 20, 62, 20, console::LightBrake},
    {63, 20, 63, 31, console::LightTailReverse}, {45, 21, 46, 27, console::LightTailReverse}, {61, 21, 62, 29, console::LightTailReverse}, {45, 28, 45, 31, console::LightTailReverse},
    {46, 28, 46, 28, console::LightBrake}, {46, 29, 46, 29, console::LightTailReverse}, {46, 30, 46, 30, console::LightBrake}, {61, 30, 61, 31, console::LightTailReverse},
    {62, 30, 62, 30, console::LightBrake}, {46, 31, 46, 31, console::LightTailReverse}, {62, 31, 62, 31, console::LightTailReverse},
    // cubanbody64detail_ca
    {32, 32, 47, 47, console::LightHead}, {33, 48, 33, 49, console::LightReverse}, {34, 48, 63, 63, console::LightTailReverse}, {33, 50, 33, 50, console::LightBrake},
    {33, 51, 33, 53, console::LightTailReverse}, {33, 54, 33, 55, console::LightBrake}, {33, 56, 33, 57, console::LightTailReverse}, {33, 58, 33, 58, console::LightBrake},
    {33, 59, 33, 63, console::LightTailReverse},
    // ca_fbi_rancherbits
    {15, 0, 15, 1, console::LightReverse}, {16, 0, 30, 27, console::LightTailReverse}, {15, 2, 15, 3, console::LightBrake}, {15, 4, 15, 27, console::LightTailReverse},
    {0, 28, 30, 40, console::LightHead}, {0, 41, 4, 44, console::LightHead}, {7, 41, 18, 41, console::LightHead}, {21, 41, 30, 41, console::LightHead},
    {5, 42, 6, 44, console::LightHead}, {9, 42, 22, 44, console::LightHead}, {25, 42, 30, 44, console::LightHead}, {7, 43, 8, 44, console::LightHead},
    {23, 43, 24, 44, console::LightHead},
    // gangburbit2
    {14, 4, 18, 11, console::LightHead}, {11, 5, 13, 10, console::LightHead}, {19, 5, 21, 10, console::LightHead}, {9, 6, 10, 15, console::LightHead},
    {22, 6, 23, 11, console::LightHead}, {8, 7, 8, 15, console::LightHead}, {24, 7, 24, 11, console::LightHead}, {7, 8, 7, 15, console::LightHead},
    {25, 8, 25, 12, console::LightHead}, {26, 9, 26, 9, console::LightReverse}, {6, 10, 6, 20, console::LightHead}, {26, 10, 26, 12, console::LightHead},
    {11, 11, 12, 14, console::LightHead}, {19, 11, 19, 11, console::LightHead}, {27, 11, 27, 11, console::LightReverse}, {5, 12, 5, 17, console::LightHead},
    {13, 12, 13, 15, console::LightHead}, {18, 12, 18, 12, console::LightHead}, {20, 12, 21, 15, console::LightHead}, {27, 12, 27, 17, console::LightHead},
    {19, 13, 19, 14, console::LightHead}, {22, 13, 22, 14, console::LightHead}, {14, 14, 15, 14, console::LightHead}, {23, 14, 23, 16, console::LightHead},
    {12, 15, 12, 15, console::LightHead}, {14, 15, 14, 15, console::LightHead}, {24, 15, 24, 15, console::LightHead}, {26, 15, 26, 19, console::LightHead},
    {9, 16, 9, 16, console::LightHead}, {19, 16, 19, 25, console::LightHead}, {22, 16, 22, 16, console::LightHead}, {25, 16, 25, 16, console::LightHead},
    {18, 17, 18, 17, console::LightHead}, {5, 18, 5, 18, console::LightReverse}, {7, 18, 7, 21, console::LightHead}, {16, 18, 17, 18, console::LightHead},
    {20, 18, 22, 20, console::LightHead}, {25, 18, 25, 19, console::LightHead}, {27, 18, 27, 19, console::LightReverse}, {8, 19, 8, 22, console::LightHead},
    {18, 19, 18, 20, console::LightHead}, {24, 19, 24, 19, console::LightHead}, {17, 20, 17, 20, console::LightHead}, {23, 20, 23, 21, console::LightHead},
    {26, 20, 26, 20, console::LightReverse}, {20, 21, 20, 23, console::LightHead}, {22, 21, 22, 22, console::LightHead}, {25, 21, 25, 21, console::LightHead},
    {9, 22, 9, 23, console::LightHead}, {18, 22, 18, 25, console::LightHead}, {21, 22, 21, 22, console::LightHead}, {24, 22, 24, 22, console::LightHead},
    {25, 22, 25, 22, console::LightReverse}, {10, 23, 11, 23, console::LightHead}, {10, 24, 10, 24, console::LightReverse}, {11, 24, 12, 24, console::LightHead},
    {17, 24, 17, 25, console::LightHead}, {21, 24, 21, 24, console::LightHead}, {22, 24, 22, 24, console::LightReverse}, {12, 25, 12, 25, console::LightReverse},
    {13, 25, 16, 25, console::LightHead}, {20, 25, 20, 25, console::LightReverse}, {54, 55, 54, 55, console::LightReverse}, {55, 55, 59, 60, console::LightTailReverse},
    {60, 55, 61, 55, console::LightReverse}, {62, 55, 64, 55, console::LightTailReverse}, {54, 56, 54, 62, console::LightTailReverse}, {60, 56, 63, 63, console::LightTailReverse},
    {64, 56, 64, 56, console::LightReverse}, {64, 57, 64, 57, console::LightTailReverse}, {64, 58, 64, 59, console::LightReverse}, {64, 60, 64, 60, console::LightTailReverse},
    {55, 61, 58, 62, console::LightTailReverse}, {59, 61, 59, 61, console::LightReverse}, {64, 61, 64, 63, console::LightReverse}, {59, 62, 59, 63, console::LightTailReverse},
    {54, 63, 54, 64, console::LightReverse}, {55, 63, 56, 63, console::LightTailReverse}, {57, 63, 57, 64, console::LightReverse}, {58, 63, 58, 64, console::LightTailReverse},
    {55, 64, 56, 64, console::LightReverse}, {59, 64, 59, 64, console::LightReverse}, {60, 64, 60, 64, console::LightTailReverse}, {61, 64, 61, 64, console::LightReverse},
    {62, 64, 64, 64, console::LightTailReverse},
    // infernus_bitsca
    {0, 0, 15, 15, console::LightHead}, {16, 0, 31, 15, console::LightTailReverse},
    // vcs_reginabit
    {0, 16, 31, 31, console::LightHead}, {48, 16, 62, 29, console::LightTailReverse}, {63, 16, 63, 16, console::LightBrake}, {63, 17, 63, 31, console::LightTailReverse},
    {48, 30, 48, 30, console::LightBrake}, {49, 30, 62, 30, console::LightTailReverse}, {48, 31, 60, 31, console::LightTailReverse}, {61, 31, 61, 31, console::LightBrake},
    {62, 31, 62, 31, console::LightTailReverse},
    // sabre_details1
    {0, 18, 12, 31, console::LightHead}, {13, 18, 30, 31, console::LightTailReverse}, {13, 32, 13, 32, console::LightReverse}, {14, 32, 30, 32, console::LightTailReverse},
    // vcs_sentbit
    {16, 0, 47, 15, console::LightHead}, {0, 32, 3, 32, console::LightBrake}, {4, 32, 7, 32, console::LightReverse}, {8, 32, 9, 32, console::LightBrake},
    {10, 32, 10, 47, console::LightTailReverse}, {11, 32, 11, 32, console::LightReverse}, {12, 32, 12, 32, console::LightBrake}, {13, 32, 16, 47, console::LightTailReverse},
    {17, 32, 20, 32, console::LightReverse}, {21, 32, 23, 45, console::LightTailReverse}, {24, 32, 25, 32, console::LightReverse}, {26, 32, 26, 32, console::LightBrake},
    {27, 32, 27, 32, console::LightReverse}, {28, 32, 28, 32, console::LightBrake}, {29, 32, 29, 47, console::LightTailReverse}, {30, 32, 39, 32, console::LightReverse},
    {40, 32, 41, 32, console::LightBrake}, {42, 32, 47, 32, console::LightReverse}, {0, 33, 9, 37, console::LightTailReverse}, {11, 33, 12, 47, console::LightTailReverse},
    {17, 33, 20, 45, console::LightTailReverse}, {24, 33, 28, 47, console::LightTailReverse}, {30, 33, 47, 35, console::LightTailReverse}, {30, 36, 46, 43, console::LightTailReverse},
    {47, 36, 47, 36, console::LightReverse}, {47, 37, 47, 43, console::LightTailReverse}, {0, 38, 1, 38, console::LightReverse}, {2, 38, 9, 45, console::LightTailReverse},
    {0, 39, 1, 39, console::LightTailReverse}, {0, 40, 1, 40, console::LightReverse}, {0, 41, 1, 41, console::LightTailReverse}, {0, 42, 1, 42, console::LightReverse},
    {0, 43, 1, 43, console::LightTailReverse}, {0, 44, 1, 44, console::LightReverse}, {30, 44, 33, 47, console::LightTailReverse}, {34, 44, 35, 44, console::LightReverse},
    {36, 44, 46, 45, console::LightTailReverse}, {47, 44, 47, 44, console::LightReverse}, {0, 45, 1, 45, console::LightTailReverse}, {34, 45, 35, 45, console::LightTailReverse},
    {47, 45, 47, 45, console::LightTailReverse}, {0, 46, 2, 46, console::LightReverse}, {3, 46, 4, 46, console::LightBrake}, {5, 46, 6, 46, console::LightReverse},
    {7, 46, 7, 46, console::LightBrake}, {8, 46, 9, 47, console::LightTailReverse}, {17, 46, 19, 47, console::LightTailReverse}, {20, 46, 21, 46, console::LightBrake},
    {22, 46, 23, 47, console::LightTailReverse}, {34, 46, 35, 46, console::LightReverse}, {36, 46, 39, 47, console::LightTailReverse}, {40, 46, 41, 46, console::LightReverse},
    {42, 46, 45, 47, console::LightTailReverse}, {46, 46, 47, 47, console::LightReverse}, {0, 47, 1, 47, console::LightReverse}, {2, 47, 7, 47, console::LightTailReverse},
    {20, 47, 21, 47, console::LightTailReverse}, {34, 47, 35, 47, console::LightTailReverse}, {40, 47, 41, 47, console::LightTailReverse},
};
// Indexed by the cache ids in Models.hpp: first rect, count, reference width and height.
inline constexpr console::LightSet lightSets[] = {
    {0, 31, 128, 128}, // vcs_6atvbit
    {31, 11, 128, 128}, // admiral868bit_sl
    {42, 26, 128, 128}, // vicechee868bit128
    {68, 7, 128, 128}, // baggage8bit128
    {75, 2, 128, 128}, // banshee868bit_sl
    {77, 4, 128, 128}, // iz_perennial_interior
    {81, 47, 128, 128}, // blistac868bit_sl
    {128, 9, 128, 128}, // vcs_bobcatbit
    {137, 43, 128, 128}, // vcs_dozerbit2
    {180, 9, 128, 128}, // burritobit
    {189, 71, 128, 128}, // cabbie8bit
    {260, 16, 128, 128}, // caddy8bit128
    {276, 56, 128, 128}, // pimpbit
    {332, 64, 128, 128}, // deluxobit
    {396, 27, 64, 64}, // esperanto
    {423, 27, 128, 128}, // vc_vehicledoors_sl
    {450, 43, 128, 128}, // firetruk8bit128
    {493, 15, 64, 64}, // glendale_main64x64
    {508, 4, 128, 128}, // greenwoodbit
    {512, 6, 64, 64}, // hermesbody64detail_ca
    {518, 7, 128, 128}, // iz_idaho_interior
    {525, 6, 128, 128}, // iz_landstalker_interior
    {531, 8, 128, 128}, // iz_manana_interior
    {539, 66, 128, 128}, // vcs_mopedbit
    {605, 12, 128, 128}, // vcs_oceanicbit
    {617, 13, 128, 128}, // sanchez8bit128
    {630, 19, 64, 64}, // stallion868bit128
    {649, 54, 128, 128}, // policebits
    {703, 21, 128, 128}, // patriotbit
    {724, 10, 128, 128}, // ponybits_ca
    {734, 60, 128, 128}, // iz_sentinel86_interior
    {794, 4, 128, 128}, // pcj6008bit128
    {798, 35, 32, 32}, // linerun_lights
    {833, 45, 128, 128}, // waltonbit
    {878, 21, 128, 64}, // barracksbits
    {899, 7, 128, 128}, // flatbed868bit128
    {906, 14, 128, 128}, // armytruk8bit128
    {920, 32, 128, 128}, // iz_moonbeam_interior
    {952, 7, 64, 64}, // rumpobits_ca
    {959, 48, 128, 128}, // miami_cabbietex128
    {1007, 56, 128, 128}, // ambulan8bit128
    {1063, 8, 128, 128}, // stretchbit
    {1071, 8, 128, 128}, // faggio8bit128
    {1079, 21, 128, 128}, // vcs_quadbitv3_sjl
    {1100, 24, 128, 128}, // angel8bit128
    {1124, 9, 128, 128}, // enforcer868bit128
    {1133, 20, 128, 128}, // boxville868bit128
    {1153, 22, 128, 128}, // benson_bits
    {1175, 5, 128, 128}, // coach868bit128
    {1180, 8, 128, 128}, // mule8bit128
    {1188, 5, 128, 128}, // voodoobit
    {1193, 17, 128, 128}, // securica868bit128
    {1210, 14, 128, 128}, // trash868bit128
    {1224, 14, 128, 128}, // yankee_bits
    {1238, 6, 128, 128}, // mrwhoo868bit128
    {1244, 10, 128, 128}, // sandkingbit
    {1254, 18, 128, 128}, // forkbit
    {1272, 93, 128, 128}, // vcs_streetfighterbit
    {1365, 49, 128, 128}, // virgobit
    {1414, 6, 128, 128}, // stingerbit
    {1420, 10, 128, 128}, // bfinject868bit128
    {1430, 16, 128, 128}, // pheonixbit
    {1446, 2, 128, 128}, // mesabit
    {1448, 5, 64, 64}, // chollo_details1
    {1453, 27, 128, 128}, // vcs_cometbit
    {1480, 9, 64, 64}, // cubanbody64detail_ca
    {1489, 13, 128, 128}, // ca_fbi_rancherbits
    {1502, 85, 128, 128}, // gangburbit2
    {1587, 2, 64, 64}, // infernus_bitsca
    {1589, 9, 128, 128}, // vcs_reginabit
    {1598, 4, 64, 64}, // sabre_details1
    {1602, 59, 128, 128}, // vcs_sentbit
};
}
