#pragma once
// Generated by tools/vehicle-lights/generate.py from textures/GTALCS. Do not edit.
#include "../Shared/Console/VehicleLights.hpp"
namespace vehicle {
// Light rectangles in texels of the reference size (inclusive bounds).
inline constexpr console::LightRect lightRects[] = {
    // ferrarif3558bit128
    {16, 112, 16, 112, console::LightBrake}, {17, 112, 30, 127, console::LightTailReverse}, {31, 112, 31, 112, console::LightBrake}, {96, 112, 127, 127, console::LightHead},
    {16, 113, 16, 126, console::LightTailReverse}, {31, 113, 31, 126, console::LightTailReverse}, {16, 127, 16, 127, console::LightBrake}, {31, 127, 31, 127, console::LightBrake},
    // landstal8bit128
    {64, 80, 94, 82, console::LightHead}, {64, 83, 69, 83, console::LightHead}, {73, 83, 94, 83, console::LightHead}, {64, 84, 68, 93, console::LightHead},
    {74, 84, 82, 93, console::LightHead}, {92, 84, 94, 84, console::LightHead}, {73, 85, 73, 93, console::LightHead}, {83, 85, 85, 93, console::LightHead},
    {93, 85, 94, 88, console::LightHead}, {69, 86, 70, 93, console::LightHead}, {86, 86, 91, 87, console::LightHead}, {71, 87, 72, 93, console::LightHead},
    {86, 88, 87, 94, console::LightHead}, {89, 88, 91, 94, console::LightHead}, {88, 89, 88, 94, console::LightHead}, {94, 89, 94, 94, console::LightHead},
    {92, 90, 93, 94, console::LightHead}, {85, 94, 85, 94, console::LightHead}, {113, 97, 126, 107, console::LightTailReverse}, {113, 108, 125, 116, console::LightTailReverse},
    {126, 108, 126, 109, console::LightReverse}, {126, 110, 126, 116, console::LightTailReverse},
    // idaho8bit128
    {97, 72, 112, 77, console::LightTailReverse}, {113, 72, 126, 78, console::LightReverse}, {97, 78, 111, 78, console::LightBrake}, {97, 82, 109, 93, console::LightHead},
    {114, 98, 125, 110, console::LightHead}, {114, 114, 125, 126, console::LightHead},
    // stinger8bit128
    {96, 96, 127, 109, console::LightTailReverse}, {96, 110, 123, 111, console::LightTailReverse}, {124, 110, 125, 110, console::LightBrake}, {126, 110, 127, 111, console::LightTailReverse},
    {124, 111, 125, 111, console::LightTailReverse}, {18, 112, 29, 115, console::LightReverse}, {95, 112, 127, 117, console::LightHead}, {17, 113, 17, 126, console::LightReverse},
    {30, 113, 30, 126, console::LightReverse}, {16, 114, 16, 125, console::LightReverse}, {31, 114, 31, 126, console::LightReverse}, {18, 116, 18, 116, console::LightReverse},
    {20, 116, 29, 119, console::LightReverse}, {19, 117, 19, 127, console::LightReverse}, {18, 118, 18, 127, console::LightReverse}, {95, 118, 103, 122, console::LightHead},
    {105, 118, 127, 120, console::LightHead}, {104, 119, 104, 127, console::LightHead}, {20, 120, 20, 127, console::LightReverse}, {24, 120, 29, 124, console::LightReverse},
    {21, 121, 23, 127, console::LightReverse}, {107, 121, 127, 123, console::LightHead}, {105, 122, 105, 127, console::LightHead}, {95, 123, 101, 126, console::LightHead},
    {106, 123, 106, 127, console::LightHead}, {102, 124, 103, 127, console::LightHead}, {107, 124, 108, 127, console::LightHead}, {110, 124, 127, 127, console::LightHead},
    {24, 125, 25, 127, console::LightReverse}, {27, 125, 29, 127, console::LightReverse}, {109, 125, 109, 127, console::LightHead}, {26, 126, 26, 127, console::LightReverse},
    {96, 127, 101, 127, console::LightHead},
    // linerun8bit128
    {96, 96, 110, 104, console::LightTailReverse}, {111, 96, 111, 96, console::LightBrake}, {111, 97, 111, 97, console::LightTailReverse}, {111, 98, 111, 99, console::LightBrake},
    {111, 100, 111, 110, console::LightTailReverse}, {96, 105, 96, 105, console::LightBrake}, {97, 105, 110, 111, console::LightTailReverse}, {96, 106, 96, 111, console::LightTailReverse},
    {111, 111, 111, 111, console::LightBrake}, {96, 112, 110, 126, console::LightReverse}, {111, 112, 127, 125, console::LightHead}, {111, 126, 111, 126, console::LightReverse},
    {112, 126, 127, 126, console::LightHead}, {96, 127, 103, 127, console::LightReverse}, {108, 127, 110, 127, console::LightReverse}, {111, 127, 121, 127, console::LightHead},
    {124, 127, 127, 127, console::LightHead},
    // peren8bit128
    {113, 97, 126, 109, console::LightTailReverse}, {96, 112, 111, 126, console::LightHead}, {96, 127, 103, 127, console::LightHead}, {108, 127, 111, 127, console::LightHead},
    // sentinel8bit128
    {95, 64, 95, 79, console::LightReverse}, {96, 64, 110, 79, console::LightTailReverse}, {111, 64, 111, 64, console::LightTail}, {112, 64, 127, 70, console::LightHead},
    {111, 65, 111, 65, console::LightTailReverse}, {111, 66, 111, 79, console::LightTail}, {112, 71, 112, 79, console::LightHead}, {114, 71, 127, 77, console::LightHead},
    {113, 72, 113, 79, console::LightHead}, {114, 78, 126, 78, console::LightHead}, {96, 80, 111, 85, console::LightReverse}, {112, 80, 126, 95, console::LightTailReverse},
    {127, 80, 127, 80, console::LightTail}, {127, 81, 127, 81, console::LightTailReverse}, {127, 82, 127, 95, console::LightTail}, {97, 86, 111, 94, console::LightReverse},
    {96, 88, 96, 91, console::LightReverse}, {111, 95, 111, 95, console::LightReverse},
    // patriot8bit128
    {112, 96, 125, 104, console::LightTailReverse}, {126, 96, 127, 96, console::LightBrake}, {126, 97, 127, 109, console::LightTailReverse}, {112, 105, 112, 107, console::LightBrake},
    {113, 105, 125, 109, console::LightTailReverse}, {112, 108, 112, 110, console::LightTailReverse}, {113, 110, 117, 110, console::LightTailReverse}, {118, 110, 124, 110, console::LightBrake},
    {125, 110, 126, 110, console::LightTailReverse}, {127, 110, 127, 110, console::LightBrake}, {112, 111, 115, 111, console::LightBrake}, {112, 112, 127, 126, console::LightHead},
    {112, 127, 119, 127, console::LightHead}, {124, 127, 127, 127, console::LightHead},
    // firetruk8bit128
    {96, 96, 111, 110, console::LightHead}, {112, 96, 125, 104, console::LightTailReverse}, {126, 96, 127, 96, console::LightBrake}, {126, 97, 127, 109, console::LightTailReverse},
    {112, 105, 112, 107, console::LightBrake}, {113, 105, 125, 109, console::LightTailReverse}, {112, 108, 112, 110, console::LightTailReverse}, {113, 110, 117, 110, console::LightTailReverse},
    {118, 110, 124, 110, console::LightBrake}, {125, 110, 126, 110, console::LightTailReverse}, {127, 110, 127, 110, console::LightBrake}, {96, 111, 103, 111, console::LightHead},
    {112, 111, 115, 111, console::LightBrake}, {116, 111, 116, 111, console::LightReverse},
    // trash8bit128
    {96, 96, 111, 110, console::LightHead}, {112, 96, 125, 104, console::LightTailReverse}, {126, 96, 127, 96, console::LightBrake}, {126, 97, 127, 109, console::LightTailReverse},
    {112, 105, 112, 107, console::LightBrake}, {113, 105, 125, 109, console::LightTailReverse}, {112, 108, 112, 110, console::LightTailReverse}, {113, 110, 117, 110, console::LightTailReverse},
    {118, 110, 124, 110, console::LightBrake}, {125, 110, 126, 110, console::LightTailReverse}, {127, 110, 127, 110, console::LightBrake}, {96, 111, 103, 111, console::LightHead},
    {108, 111, 111, 111, console::LightHead}, {112, 111, 115, 111, console::LightBrake}, {116, 111, 116, 111, console::LightReverse},
    // stretch8bit128
    {80, 0, 111, 14, console::LightHead}, {80, 15, 87, 15, console::LightHead}, {92, 15, 103, 15, console::LightHead}, {108, 15, 111, 15, console::LightHead},
    {112, 64, 127, 78, console::LightReverse}, {112, 79, 117, 79, console::LightReverse}, {112, 80, 120, 94, console::LightTailReverse}, {121, 80, 121, 81, console::LightBrake},
    {122, 80, 127, 94, console::LightTailReverse}, {121, 82, 121, 94, console::LightTailReverse}, {113, 95, 119, 95, console::LightTailReverse}, {120, 95, 121, 95, console::LightBrake},
    {123, 95, 126, 95, console::LightBrake},
    // mananab8bit128
    {72, 80, 95, 95, console::LightHead}, {113, 97, 126, 116, console::LightTailReverse}, {127, 111, 127, 111, console::LightReverse}, {127, 112, 127, 113, console::LightTailReverse},
    {127, 114, 127, 115, console::LightBrake}, {127, 116, 127, 117, console::LightReverse}, {113, 117, 113, 117, console::LightBrake}, {114, 117, 126, 117, console::LightTailReverse},
    {119, 118, 121, 118, console::LightReverse},
    // infernus8bit128
    {16, 112, 21, 112, console::LightBrake}, {22, 112, 27, 112, console::LightReverse}, {28, 112, 28, 112, console::LightBrake}, {29, 112, 29, 112, console::LightReverse},
    {30, 112, 30, 112, console::LightBrake}, {96, 112, 127, 118, console::LightHead}, {16, 113, 31, 126, console::LightTailReverse}, {96, 119, 124, 119, console::LightHead},
    {126, 119, 127, 126, console::LightHead}, {96, 120, 99, 127, console::LightHead}, {101, 120, 125, 127, console::LightHead}, {100, 121, 100, 127, console::LightHead},
    {16, 127, 16, 127, console::LightBrake}, {17, 127, 30, 127, console::LightTailReverse}, {31, 127, 31, 127, console::LightBrake},
    // blista8bit128
    {64, 64, 87, 70, console::LightHead}, {64, 71, 82, 73, console::LightHead}, {85, 71, 87, 79, console::LightHead}, {83, 72, 84, 79, console::LightHead},
    {64, 74, 73, 74, console::LightHead}, {75, 74, 82, 79, console::LightHead}, {64, 75, 69, 79, console::LightHead}, {71, 75, 74, 79, console::LightHead},
    {70, 76, 70, 79, console::LightHead}, {112, 96, 114, 104, console::LightTailReverse}, {115, 96, 115, 96, console::LightBrake}, {116, 96, 126, 111, console::LightTailReverse},
    {127, 96, 127, 96, console::LightBrake}, {115, 97, 115, 111, console::LightTailReverse}, {127, 97, 127, 98, console::LightTailReverse}, {127, 100, 127, 111, console::LightTailReverse},
    {112, 105, 112, 106, console::LightBrake}, {113, 105, 114, 111, console::LightTailReverse}, {112, 107, 112, 111, console::LightTailReverse}, {112, 112, 127, 126, console::LightReverse},
    {112, 127, 118, 127, console::LightReverse}, {126, 127, 127, 127, console::LightReverse},
    // pony8bit128
    {120, 65, 126, 79, console::LightTailReverse}, {120, 80, 125, 80, console::LightTailReverse}, {126, 80, 126, 80, console::LightBrake}, {97, 81, 110, 94, console::LightHead},
    {120, 81, 126, 94, console::LightReverse},
    // mule8bit128
    {113, 64, 113, 64, console::LightBrake}, {114, 64, 115, 95, console::LightTailReverse}, {116, 64, 116, 64, console::LightBrake}, {117, 64, 122, 94, console::LightTailReverse},
    {123, 64, 127, 64, console::LightBrake}, {113, 65, 113, 94, console::LightTailReverse}, {116, 65, 116, 95, console::LightTailReverse}, {123, 65, 127, 91, console::LightTailReverse},
    {112, 66, 112, 69, console::LightBrake}, {112, 70, 112, 71, console::LightReverse}, {112, 72, 112, 73, console::LightBrake}, {112, 80, 112, 85, console::LightBrake},
    {95, 85, 110, 95, console::LightHead}, {112, 86, 112, 87, console::LightReverse}, {112, 88, 112, 90, console::LightBrake}, {112, 91, 112, 91, console::LightReverse},
    {123, 92, 126, 94, console::LightTailReverse}, {127, 92, 127, 93, console::LightBrake}, {127, 94, 127, 94, console::LightTailReverse}, {113, 95, 113, 95, console::LightBrake},
    {117, 95, 119, 95, console::LightTailReverse}, {120, 95, 123, 95, console::LightBrake}, {124, 95, 124, 95, console::LightTailReverse}, {125, 95, 125, 95, console::LightBrake},
    {126, 95, 126, 95, console::LightTailReverse}, {127, 95, 127, 95, console::LightBrake},
    // cheetah8bit128
    {48, 80, 63, 94, console::LightHead}, {68, 81, 68, 81, console::LightBrake}, {69, 81, 90, 87, console::LightTailReverse}, {91, 81, 93, 81, console::LightBrake},
    {94, 81, 95, 87, console::LightTailReverse}, {66, 82, 68, 92, console::LightTailReverse}, {91, 82, 93, 87, console::LightTailReverse}, {65, 84, 65, 87, console::LightTailReverse},
    {65, 88, 65, 90, console::LightBrake}, {69, 88, 81, 93, console::LightTailReverse}, {82, 88, 95, 94, console::LightReverse}, {66, 93, 66, 93, console::LightBrake},
    {67, 93, 68, 93, console::LightTailReverse}, {68, 94, 77, 94, console::LightBrake}, {78, 94, 79, 94, console::LightTailReverse}, {80, 94, 81, 94, console::LightBrake},
    {48, 95, 56, 95, console::LightHead}, {62, 95, 62, 95, console::LightHead},
    // ambulan8bit128
    {96, 96, 111, 110, console::LightHead}, {112, 96, 125, 104, console::LightTailReverse}, {126, 96, 127, 96, console::LightBrake}, {126, 97, 127, 109, console::LightTailReverse},
    {112, 105, 112, 107, console::LightBrake}, {113, 105, 125, 109, console::LightTailReverse}, {112, 108, 112, 110, console::LightTailReverse}, {113, 110, 117, 110, console::LightTailReverse},
    {118, 110, 124, 110, console::LightBrake}, {125, 110, 126, 110, console::LightTailReverse}, {127, 110, 127, 110, console::LightBrake}, {96, 111, 103, 111, console::LightHead},
    {112, 111, 115, 111, console::LightBrake},
    // police8bit128
    {68, 65, 108, 71, console::LightTailReverse}, {66, 66, 67, 76, console::LightTailReverse}, {109, 66, 109, 76, console::LightTailReverse}, {65, 68, 65, 71, console::LightTailReverse},
    {110, 68, 110, 74, console::LightTailReverse}, {65, 72, 65, 74, console::LightBrake}, {68, 72, 81, 77, console::LightTailReverse}, {82, 72, 95, 78, console::LightReverse},
    {96, 72, 108, 77, console::LightTailReverse}, {66, 77, 66, 77, console::LightBrake}, {67, 77, 67, 77, console::LightTailReverse}, {109, 77, 109, 77, console::LightBrake},
    {68, 78, 77, 78, console::LightBrake}, {78, 78, 79, 78, console::LightTailReverse}, {80, 78, 81, 78, console::LightBrake}, {96, 78, 105, 78, console::LightTailReverse},
    {106, 78, 106, 78, console::LightBrake}, {107, 78, 107, 78, console::LightTailReverse}, {65, 81, 87, 93, console::LightHead}, {65, 94, 69, 94, console::LightHead},
    {75, 94, 87, 94, console::LightHead},
    // moonbeam8bit128
    {96, 64, 96, 64, console::LightBrake}, {97, 64, 114, 78, console::LightTailReverse}, {115, 64, 115, 64, console::LightBrake}, {116, 64, 126, 78, console::LightTailReverse},
    {96, 65, 96, 77, console::LightTailReverse}, {115, 65, 115, 78, console::LightTailReverse}, {127, 65, 127, 65, console::LightBrake}, {127, 66, 127, 75, console::LightTailReverse},
    {127, 76, 127, 76, console::LightBrake}, {127, 77, 127, 77, console::LightTailReverse}, {96, 78, 96, 78, console::LightBrake}, {127, 78, 127, 78, console::LightBrake},
    {97, 79, 97, 79, console::LightBrake}, {98, 79, 111, 79, console::LightTailReverse}, {112, 79, 126, 79, console::LightBrake}, {98, 82, 109, 93, console::LightHead},
    // esperanto8bit128
    {97, 71, 98, 71, console::LightBrake}, {99, 71, 100, 77, console::LightTailReverse}, {101, 71, 101, 71, console::LightBrake}, {102, 71, 105, 77, console::LightTailReverse},
    {106, 71, 108, 71, console::LightBrake}, {109, 71, 112, 76, console::LightTailReverse}, {113, 71, 125, 77, console::LightReverse}, {97, 72, 98, 77, console::LightTailReverse},
    {101, 72, 101, 77, console::LightTailReverse}, {106, 72, 108, 77, console::LightTailReverse}, {126, 72, 126, 77, console::LightReverse}, {109, 77, 111, 77, console::LightTailReverse},
    {112, 77, 112, 77, console::LightBrake}, {115, 84, 125, 92, console::LightHead},
    // taxi8bit128
    {68, 65, 107, 71, console::LightTailReverse}, {66, 66, 67, 76, console::LightTailReverse}, {108, 66, 108, 77, console::LightTailReverse}, {109, 66, 109, 66, console::LightBrake},
    {109, 67, 109, 76, console::LightTailReverse}, {65, 68, 65, 71, console::LightTailReverse}, {110, 68, 110, 73, console::LightTailReverse}, {65, 72, 65, 75, console::LightBrake},
    {68, 72, 81, 77, console::LightTailReverse}, {82, 72, 95, 78, console::LightReverse}, {96, 72, 107, 77, console::LightTailReverse}, {110, 74, 110, 74, console::LightBrake},
    {66, 77, 66, 77, console::LightBrake}, {67, 77, 67, 77, console::LightTailReverse}, {109, 77, 109, 77, console::LightBrake}, {68, 78, 77, 78, console::LightBrake},
    {78, 78, 79, 78, console::LightTailReverse}, {80, 78, 81, 78, console::LightBrake}, {96, 78, 103, 78, console::LightTailReverse}, {104, 78, 107, 78, console::LightBrake},
    {65, 81, 87, 94, console::LightHead},
    // kuruma8bit128
    {72, 80, 95, 95, console::LightHead}, {113, 106, 113, 106, console::LightBrake}, {114, 106, 126, 126, console::LightTailReverse}, {127, 106, 127, 107, console::LightReverse},
    {113, 107, 113, 126, console::LightTailReverse}, {127, 108, 127, 109, console::LightBrake}, {127, 110, 127, 111, console::LightTailReverse}, {127, 112, 127, 115, console::LightReverse},
    {127, 124, 127, 124, console::LightReverse}, {113, 127, 113, 127, console::LightReverse}, {121, 127, 121, 127, console::LightReverse},
    // bobcat8bit128
    {96, 64, 111, 78, console::LightReverse}, {112, 64, 120, 78, console::LightTailReverse}, {121, 64, 121, 65, console::LightBrake}, {122, 64, 127, 78, console::LightTailReverse},
    {121, 66, 121, 78, console::LightTailReverse}, {96, 79, 103, 79, console::LightReverse}, {113, 79, 119, 79, console::LightTailReverse}, {120, 79, 121, 79, console::LightBrake},
    {123, 79, 126, 79, console::LightBrake}, {109, 81, 109, 81, console::LightReverse}, {110, 81, 115, 87, console::LightHead}, {116, 81, 116, 81, console::LightReverse},
    {107, 82, 109, 93, console::LightHead}, {116, 82, 118, 93, console::LightHead}, {105, 83, 106, 92, console::LightHead}, {119, 83, 120, 92, console::LightHead},
    {104, 84, 104, 92, console::LightHead}, {121, 84, 121, 92, console::LightHead}, {103, 85, 103, 91, console::LightHead}, {122, 85, 122, 91, console::LightHead},
    {123, 86, 123, 86, console::LightReverse}, {102, 87, 102, 89, console::LightHead}, {123, 87, 123, 89, console::LightHead}, {110, 88, 111, 88, console::LightHead},
    {113, 88, 115, 94, console::LightHead}, {111, 89, 112, 94, console::LightHead}, {110, 90, 110, 94, console::LightHead}, {106, 93, 106, 93, console::LightHead},
    {119, 93, 119, 93, console::LightHead}, {108, 94, 109, 94, console::LightHead}, {116, 94, 117, 94, console::LightHead},
    // mrwhoop8bit128
    {107, 97, 125, 109, console::LightTailReverse}, {126, 98, 126, 108, console::LightTailReverse}, {107, 110, 124, 110, console::LightTailReverse}, {125, 110, 125, 110, console::LightBrake},
    {104, 112, 127, 127, console::LightHead},
    // bfinject8bit128
    {16, 112, 17, 115, console::LightTailReverse}, {18, 112, 18, 112, console::LightReverse}, {19, 112, 30, 112, console::LightTailReverse}, {31, 112, 31, 112, console::LightBrake},
    {18, 113, 25, 126, console::LightTailReverse}, {26, 113, 26, 113, console::LightBrake}, {27, 113, 31, 118, console::LightTailReverse}, {26, 114, 26, 127, console::LightTailReverse},
    {16, 116, 16, 116, console::LightBrake}, {17, 116, 17, 126, console::LightTailReverse}, {16, 117, 16, 126, console::LightTailReverse}, {27, 119, 29, 127, console::LightTailReverse},
    {30, 119, 30, 119, console::LightBrake}, {31, 119, 31, 127, console::LightTailReverse}, {30, 120, 30, 127, console::LightTailReverse}, {16, 127, 17, 127, console::LightBrake},
    {18, 127, 20, 127, console::LightTailReverse}, {21, 127, 21, 127, console::LightBrake}, {22, 127, 22, 127, console::LightTailReverse}, {23, 127, 23, 127, console::LightBrake},
    {24, 127, 25, 127, console::LightTailReverse},
    // enforcer8bit128
    {112, 80, 127, 85, console::LightReverse}, {112, 86, 117, 95, console::LightReverse}, {119, 86, 127, 94, console::LightReverse}, {118, 87, 118, 95, console::LightReverse},
    {119, 95, 119, 95, console::LightReverse}, {126, 95, 127, 95, console::LightReverse}, {96, 96, 104, 110, console::LightTailReverse}, {105, 96, 105, 97, console::LightBrake},
    {106, 96, 111, 110, console::LightTailReverse}, {105, 98, 105, 110, console::LightTailReverse}, {97, 111, 103, 111, console::LightTailReverse}, {104, 111, 105, 111, console::LightBrake},
    {107, 111, 110, 111, console::LightBrake}, {112, 112, 127, 117, console::LightHead}, {112, 118, 117, 125, console::LightHead}, {119, 118, 127, 127, console::LightHead},
    {118, 119, 118, 127, console::LightHead}, {113, 126, 117, 127, console::LightHead},
    // securica8bit128
    {111, 64, 111, 72, console::LightReverse}, {112, 64, 114, 72, console::LightTailReverse}, {115, 64, 115, 64, console::LightBrake}, {116, 64, 126, 79, console::LightTailReverse},
    {127, 64, 127, 64, console::LightReverse}, {115, 65, 115, 79, console::LightTailReverse}, {127, 65, 127, 66, console::LightTailReverse}, {127, 67, 127, 67, console::LightReverse},
    {127, 68, 127, 79, console::LightTailReverse}, {112, 73, 112, 74, console::LightReverse}, {113, 73, 114, 79, console::LightTailReverse}, {111, 75, 111, 79, console::LightReverse},
    {112, 75, 112, 79, console::LightTailReverse}, {96, 80, 111, 94, console::LightHead}, {112, 80, 127, 94, console::LightReverse}, {96, 95, 103, 95, console::LightHead},
    {112, 95, 118, 95, console::LightReverse},
    // banshee8bit128
    {96, 96, 127, 107, console::LightTailReverse}, {96, 108, 127, 111, console::LightReverse}, {96, 112, 127, 127, console::LightHead},
    // bus8bit128
    {64, 32, 77, 40, console::LightTailReverse}, {78, 32, 79, 32, console::LightBrake}, {78, 33, 79, 45, console::LightTailReverse}, {64, 41, 64, 43, console::LightBrake},
    {65, 41, 77, 45, console::LightTailReverse}, {64, 44, 64, 46, console::LightTailReverse}, {65, 46, 69, 46, console::LightTailReverse}, {70, 46, 76, 46, console::LightBrake},
    {77, 46, 78, 46, console::LightTailReverse}, {79, 46, 79, 46, console::LightBrake}, {64, 47, 67, 47, console::LightBrake}, {80, 48, 95, 63, console::LightHead},
    {109, 79, 109, 94, console::LightReverse}, {96, 80, 108, 94, console::LightReverse}, {110, 80, 111, 94, console::LightReverse}, {96, 95, 101, 95, console::LightReverse},
    // armytruk8bit128
    {64, 32, 77, 40, console::LightTailReverse}, {78, 32, 79, 32, console::LightBrake}, {78, 33, 79, 45, console::LightTailReverse}, {64, 41, 64, 43, console::LightBrake},
    {65, 41, 77, 45, console::LightTailReverse}, {64, 44, 64, 46, console::LightTailReverse}, {65, 46, 69, 46, console::LightTailReverse}, {70, 46, 76, 46, console::LightBrake},
    {77, 46, 78, 46, console::LightTailReverse}, {79, 46, 79, 46, console::LightBrake}, {64, 47, 67, 47, console::LightBrake}, {80, 48, 95, 62, console::LightHead},
    {80, 63, 89, 63, console::LightHead}, {94, 63, 95, 63, console::LightHead}, {96, 80, 111, 94, console::LightReverse}, {96, 95, 103, 95, console::LightReverse},
    // coach8bit128
    {99, 2, 111, 30, console::LightReverse}, {112, 2, 125, 60, console::LightTailReverse}, {5, 25, 5, 45, console::LightHead}, {4, 26, 4, 61, console::LightHead},
    {6, 26, 6, 61, console::LightHead}, {3, 27, 3, 61, console::LightHead}, {7, 27, 8, 33, console::LightHead}, {2, 28, 2, 61, console::LightHead},
    {9, 28, 9, 61, console::LightHead}, {10, 29, 10, 61, console::LightHead}, {11, 30, 11, 61, console::LightHead}, {12, 32, 12, 61, console::LightHead},
    {13, 33, 14, 61, console::LightHead}, {7, 34, 7, 61, console::LightHead}, {8, 35, 8, 61, console::LightHead}, {5, 50, 5, 61, console::LightHead},
    {112, 61, 112, 61, console::LightBrake}, {113, 61, 125, 61, console::LightTailReverse},
    // cabbie8bit128
    {97, 8, 111, 12, console::LightTailReverse}, {112, 8, 126, 13, console::LightReverse}, {97, 13, 97, 13, console::LightBrake}, {98, 13, 110, 13, console::LightTailReverse},
    {111, 13, 111, 13, console::LightBrake}, {102, 113, 104, 124, console::LightHead}, {105, 114, 105, 124, console::LightHead}, {99, 115, 101, 123, console::LightHead},
    {106, 115, 107, 123, console::LightHead}, {108, 116, 108, 122, console::LightHead}, {98, 117, 98, 121, console::LightHead}, {101, 124, 101, 124, console::LightHead},
    {106, 124, 106, 124, console::LightHead}, {103, 125, 103, 125, console::LightHead},
    // stallion8bit128
    {64, 0, 67, 0, console::LightBrake}, {68, 0, 77, 13, console::LightTailReverse}, {78, 0, 79, 0, console::LightBrake}, {64, 1, 67, 7, console::LightTailReverse},
    {78, 1, 79, 1, console::LightTailReverse}, {78, 2, 78, 14, console::LightTailReverse}, {79, 2, 79, 4, console::LightBrake}, {79, 5, 79, 13, console::LightTailReverse},
    {64, 8, 64, 11, console::LightBrake}, {65, 8, 67, 14, console::LightTailReverse}, {64, 12, 64, 12, console::LightTailReverse}, {64, 13, 64, 13, console::LightBrake},
    {64, 14, 64, 14, console::LightTailReverse}, {68, 14, 68, 14, console::LightTailReverse}, {69, 14, 77, 14, console::LightBrake}, {79, 14, 79, 14, console::LightBrake},
    {64, 15, 67, 15, console::LightBrake}, {108, 69, 112, 89, console::LightHead}, {104, 70, 107, 88, console::LightHead}, {113, 70, 116, 87, console::LightHead},
    {103, 71, 103, 87, console::LightHead}, {117, 71, 117, 86, console::LightHead}, {102, 72, 102, 86, console::LightHead}, {118, 72, 118, 86, console::LightHead},
    {101, 74, 101, 85, console::LightHead}, {119, 74, 119, 85, console::LightHead}, {100, 76, 100, 82, console::LightHead}, {120, 76, 120, 83, console::LightHead},
    {113, 88, 114, 88, console::LightHead}, {107, 89, 107, 89, console::LightHead}, {113, 89, 113, 89, console::LightHead},
    // rumpo8bit128
    {112, 64, 127, 78, console::LightTailReverse}, {112, 79, 112, 79, console::LightBrake}, {113, 79, 120, 79, console::LightTailReverse}, {121, 79, 124, 79, console::LightBrake},
    {125, 79, 126, 79, console::LightTailReverse}, {127, 79, 127, 79, console::LightBrake}, {101, 80, 111, 90, console::LightHead},
    // mafia8bit128
    {95, 64, 95, 79, console::LightReverse}, {96, 64, 110, 79, console::LightTailReverse}, {111, 64, 111, 64, console::LightTail}, {112, 64, 127, 70, console::LightHead},
    {111, 65, 111, 65, console::LightTailReverse}, {111, 66, 111, 79, console::LightTail}, {112, 71, 112, 79, console::LightHead}, {114, 71, 127, 77, console::LightHead},
    {113, 72, 113, 79, console::LightHead}, {114, 78, 126, 78, console::LightHead}, {96, 80, 111, 85, console::LightReverse}, {112, 80, 126, 95, console::LightTailReverse},
    {127, 80, 127, 80, console::LightTail}, {127, 81, 127, 81, console::LightTailReverse}, {127, 82, 127, 95, console::LightTail}, {97, 86, 111, 94, console::LightReverse},
    {96, 88, 96, 91, console::LightReverse}, {111, 95, 111, 95, console::LightReverse},
    // yardie8bit128
    {96, 64, 111, 75, console::LightTailReverse}, {96, 76, 110, 77, console::LightTailReverse}, {111, 76, 111, 79, console::LightBrake}, {96, 78, 96, 78, console::LightBrake},
    {97, 78, 110, 78, console::LightTailReverse}, {98, 79, 110, 79, console::LightBrake}, {112, 112, 127, 126, console::LightHead}, {112, 127, 126, 127, console::LightHead},
    // yakuza8bit128
    {96, 96, 127, 109, console::LightTailReverse}, {96, 110, 123, 111, console::LightTailReverse}, {124, 110, 125, 110, console::LightBrake}, {126, 110, 127, 111, console::LightTailReverse},
    {124, 111, 125, 111, console::LightTailReverse}, {18, 112, 29, 115, console::LightReverse}, {95, 112, 127, 117, console::LightHead}, {17, 113, 17, 126, console::LightReverse},
    {30, 113, 30, 126, console::LightReverse}, {16, 114, 16, 125, console::LightReverse}, {31, 114, 31, 126, console::LightReverse}, {18, 116, 18, 116, console::LightReverse},
    {20, 116, 29, 119, console::LightReverse}, {19, 117, 19, 127, console::LightReverse}, {18, 118, 18, 127, console::LightReverse}, {95, 118, 103, 122, console::LightHead},
    {105, 118, 127, 120, console::LightHead}, {104, 119, 104, 127, console::LightHead}, {20, 120, 20, 127, console::LightReverse}, {24, 120, 29, 124, console::LightReverse},
    {21, 121, 23, 127, console::LightReverse}, {107, 121, 127, 123, console::LightHead}, {105, 122, 105, 127, console::LightHead}, {95, 123, 101, 126, console::LightHead},
    {106, 123, 106, 127, console::LightHead}, {102, 124, 103, 127, console::LightHead}, {107, 124, 108, 127, console::LightHead}, {110, 124, 127, 127, console::LightHead},
    {24, 125, 25, 127, console::LightReverse}, {27, 125, 29, 127, console::LightReverse}, {109, 125, 109, 127, console::LightHead}, {26, 126, 26, 127, console::LightReverse},
    {96, 127, 101, 127, console::LightHead},
    // diablos8bit128
    {64, 0, 64, 0, console::LightReverse}, {65, 0, 65, 0, console::LightBrake}, {66, 0, 67, 0, console::LightReverse}, {68, 0, 69, 0, console::LightBrake},
    {70, 0, 73, 0, console::LightReverse}, {74, 0, 79, 0, console::LightBrake}, {64, 1, 64, 1, console::LightBrake}, {65, 1, 79, 2, console::LightTailReverse},
    {64, 2, 64, 9, console::LightTailReverse}, {65, 3, 78, 14, console::LightTailReverse}, {79, 3, 79, 3, console::LightBrake}, {79, 4, 79, 13, console::LightTailReverse},
    {64, 10, 64, 15, console::LightBrake}, {79, 14, 79, 14, console::LightBrake}, {65, 15, 78, 15, console::LightBrake}, {106, 69, 106, 69, console::LightReverse},
    {107, 69, 113, 71, console::LightHead}, {114, 69, 114, 69, console::LightReverse}, {104, 70, 104, 70, console::LightReverse}, {105, 70, 106, 84, console::LightHead},
    {114, 70, 115, 71, console::LightHead}, {116, 70, 116, 70, console::LightReverse}, {103, 71, 104, 81, console::LightHead}, {116, 71, 117, 86, console::LightHead},
    {102, 72, 102, 72, console::LightReverse}, {107, 72, 107, 88, console::LightHead}, {111, 72, 112, 89, console::LightHead}, {115, 72, 115, 87, console::LightHead},
    {118, 72, 118, 72, console::LightReverse}, {102, 73, 102, 81, console::LightHead}, {108, 73, 110, 89, console::LightHead}, {113, 73, 114, 88, console::LightHead},
    {118, 73, 118, 85, console::LightHead}, {101, 74, 101, 84, console::LightHead}, {119, 74, 119, 83, console::LightHead}, {100, 76, 100, 76, console::LightReverse},
    {120, 76, 120, 76, console::LightReverse}, {100, 77, 100, 81, console::LightHead}, {120, 77, 120, 81, console::LightHead}, {104, 82, 104, 82, console::LightHead},
    {102, 84, 102, 84, console::LightHead}, {119, 84, 119, 84, console::LightReverse}, {102, 85, 102, 85, console::LightReverse}, {106, 85, 106, 88, console::LightHead},
    {104, 87, 104, 87, console::LightReverse}, {105, 87, 105, 87, console::LightHead}, {116, 87, 116, 87, console::LightHead}, {105, 88, 105, 88, console::LightReverse},
    {115, 88, 115, 88, console::LightReverse}, {107, 89, 107, 89, console::LightReverse}, {113, 89, 113, 89, console::LightReverse},
    // columb8bit128
    {112, 96, 125, 104, console::LightTailReverse}, {126, 96, 127, 96, console::LightBrake}, {126, 97, 127, 109, console::LightTailReverse}, {112, 105, 112, 107, console::LightBrake},
    {113, 105, 125, 109, console::LightTailReverse}, {112, 108, 112, 110, console::LightTailReverse}, {113, 110, 117, 110, console::LightTailReverse}, {118, 110, 124, 110, console::LightBrake},
    {125, 110, 126, 110, console::LightTailReverse}, {127, 110, 127, 110, console::LightBrake}, {112, 111, 115, 111, console::LightBrake}, {112, 112, 127, 126, console::LightHead},
    {112, 127, 119, 127, console::LightHead}, {124, 127, 127, 127, console::LightHead},
    // flatbed4bit128
    {64, 32, 77, 40, console::LightTailReverse}, {78, 32, 79, 32, console::LightBrake}, {78, 33, 79, 45, console::LightTailReverse}, {64, 41, 64, 43, console::LightBrake},
    {65, 41, 77, 45, console::LightTailReverse}, {64, 44, 64, 46, console::LightTailReverse}, {65, 46, 69, 46, console::LightTailReverse}, {70, 46, 76, 46, console::LightBrake},
    {77, 46, 78, 46, console::LightTailReverse}, {79, 46, 79, 46, console::LightBrake}, {64, 47, 67, 47, console::LightBrake}, {80, 48, 95, 62, console::LightHead},
    {80, 63, 89, 63, console::LightHead}, {94, 63, 94, 63, console::LightHead},
    // yankee8bit128
    {72, 8, 87, 22, console::LightHead}, {112, 64, 114, 64, console::LightBrake}, {115, 64, 123, 95, console::LightTailReverse}, {124, 64, 126, 64, console::LightBrake},
    {112, 65, 114, 75, console::LightTailReverse}, {124, 65, 126, 95, console::LightTailReverse}, {127, 65, 127, 71, console::LightBrake}, {127, 73, 127, 78, console::LightBrake},
    {112, 76, 112, 77, console::LightBrake}, {113, 76, 114, 95, console::LightTailReverse}, {112, 78, 112, 94, console::LightTailReverse}, {127, 79, 127, 93, console::LightTailReverse},
    {95, 85, 111, 94, console::LightHead}, {127, 94, 127, 94, console::LightBrake}, {112, 95, 112, 95, console::LightBrake},
    // IJB_brg
    {68, 65, 93, 71, console::LightTailReverse}, {94, 65, 101, 65, console::LightBrake}, {102, 65, 107, 77, console::LightTailReverse}, {66, 66, 66, 66, console::LightBrake},
    {67, 66, 67, 77, console::LightTailReverse}, {94, 66, 101, 71, console::LightTailReverse}, {108, 66, 108, 77, console::LightTailReverse}, {109, 66, 109, 66, console::LightBrake},
    {66, 67, 66, 76, console::LightTailReverse}, {109, 67, 109, 76, console::LightTailReverse}, {65, 68, 65, 71, console::LightTailReverse}, {110, 68, 110, 73, console::LightTailReverse},
    {65, 72, 65, 74, console::LightBrake}, {68, 72, 81, 77, console::LightTailReverse}, {82, 72, 95, 78, console::LightReverse}, {96, 72, 101, 78, console::LightTailReverse},
    {110, 74, 110, 74, console::LightBrake}, {66, 77, 66, 77, console::LightBrake}, {109, 77, 109, 77, console::LightBrake}, {68, 78, 77, 78, console::LightBrake},
    {78, 78, 79, 78, console::LightTailReverse}, {80, 78, 81, 78, console::LightBrake}, {102, 78, 103, 78, console::LightTailReverse}, {104, 78, 107, 78, console::LightBrake},
    {65, 81, 87, 94, console::LightHead},
    // typhoon_128_interior
    {3, 25, 40, 33, console::LightTailReverse}, {3, 34, 22, 41, console::LightTailReverse}, {23, 34, 40, 41, console::LightReverse}, {14, 71, 20, 89, console::LightHead},
    {12, 72, 13, 88, console::LightHead}, {21, 72, 22, 88, console::LightHead}, {11, 73, 11, 87, console::LightHead}, {23, 73, 23, 87, console::LightHead},
    {10, 74, 10, 87, console::LightHead}, {24, 74, 24, 86, console::LightHead}, {9, 75, 9, 77, console::LightHead}, {25, 75, 25, 75, console::LightReverse},
    {25, 76, 25, 77, console::LightHead}, {8, 77, 8, 83, console::LightHead}, {26, 78, 26, 82, console::LightHead}, {9, 79, 9, 85, console::LightHead},
    {25, 79, 25, 84, console::LightHead}, {25, 85, 25, 85, console::LightReverse}, {13, 89, 13, 89, console::LightHead},
    // jm_firebirdintertior1256
    {70, 16, 70, 22, console::LightBrake}, {71, 16, 85, 16, console::LightTailReverse}, {86, 16, 86, 31, console::LightBrake}, {87, 16, 100, 18, console::LightTailReverse},
    {101, 16, 101, 17, console::LightBrake}, {71, 17, 84, 18, console::LightTailReverse}, {85, 17, 85, 17, console::LightBrake}, {85, 18, 85, 30, console::LightTailReverse},
    {101, 18, 101, 30, console::LightTailReverse}, {71, 19, 76, 19, console::LightTailReverse}, {77, 19, 81, 19, console::LightBrake}, {82, 19, 84, 30, console::LightTailReverse},
    {87, 19, 92, 19, console::LightTailReverse}, {93, 19, 97, 19, console::LightBrake}, {98, 19, 100, 31, console::LightTailReverse}, {71, 20, 74, 21, console::LightTailReverse},
    {75, 20, 78, 20, console::LightBrake}, {79, 20, 80, 31, console::LightTailReverse}, {81, 20, 81, 20, console::LightBrake}, {87, 20, 90, 20, console::LightTailReverse},
    {91, 20, 94, 20, console::LightBrake}, {95, 20, 96, 20, console::LightTailReverse}, {97, 20, 97, 21, console::LightBrake}, {75, 21, 77, 21, console::LightBrake},
    {78, 21, 78, 31, console::LightTailReverse}, {81, 21, 81, 31, console::LightTailReverse}, {87, 21, 89, 28, console::LightTailReverse}, {90, 21, 92, 21, console::LightBrake},
    {93, 21, 93, 25, console::LightReverse}, {94, 21, 94, 21, console::LightTailReverse}, {95, 21, 95, 26, console::LightReverse}, {96, 21, 96, 22, console::LightTailReverse},
    {71, 22, 73, 27, console::LightTailReverse}, {74, 22, 74, 22, console::LightBrake}, {75, 22, 77, 31, console::LightTailReverse}, {90, 22, 90, 22, console::LightBrake},
    {91, 22, 91, 31, console::LightTailReverse}, {92, 22, 92, 25, console::LightReverse}, {94, 22, 94, 25, console::LightReverse}, {97, 22, 97, 31, console::LightTailReverse},
    {74, 23, 74, 31, console::LightTailReverse}, {90, 23, 90, 31, console::LightTailReverse}, {96, 23, 96, 24, console::LightReverse}, {70, 25, 70, 26, console::LightBrake},
    {96, 25, 96, 31, console::LightTailReverse}, {92, 26, 94, 31, console::LightTailReverse}, {95, 27, 95, 31, console::LightTailReverse}, {71, 28, 71, 28, console::LightBrake},
    {72, 28, 73, 31, console::LightTailReverse}, {70, 29, 70, 29, console::LightBrake}, {71, 29, 71, 31, console::LightTailReverse}, {87, 29, 87, 30, console::LightBrake},
    {88, 29, 89, 31, console::LightTailReverse}, {70, 31, 70, 31, console::LightBrake}, {82, 31, 83, 31, console::LightTailReverse}, {84, 31, 85, 31, console::LightBrake},
    {87, 31, 87, 31, console::LightTailReverse}, {101, 31, 101, 31, console::LightBrake}, {103, 113, 124, 117, console::LightHead}, {101, 114, 102, 126, console::LightHead},
    {100, 115, 100, 126, console::LightHead}, {125, 115, 125, 122, console::LightHead}, {99, 116, 99, 126, console::LightHead}, {126, 116, 126, 116, console::LightReverse},
    {98, 117, 98, 124, console::LightHead}, {126, 117, 126, 120, console::LightHead}, {103, 118, 117, 126, console::LightHead}, {119, 118, 124, 123, console::LightHead},
    {97, 119, 97, 123, console::LightHead}, {118, 119, 118, 126, console::LightHead}, {119, 124, 122, 125, console::LightHead}, {119, 126, 119, 126, console::LightHead},
    // lotus8bit128
    {16, 112, 31, 127, console::LightTailReverse}, {96, 112, 127, 127, console::LightHead},
    // hotrod8bit128
    {92, 91, 99, 92, console::LightHead}, {90, 92, 91, 93, console::LightHead}, {100, 92, 101, 107, console::LightHead}, {89, 93, 89, 106, console::LightHead},
    {93, 93, 99, 108, console::LightHead}, {102, 93, 102, 106, console::LightHead}, {88, 94, 88, 105, console::LightHead}, {90, 94, 90, 94, console::LightHead},
    {92, 94, 92, 108, console::LightHead}, {103, 94, 103, 105, console::LightHead}, {91, 95, 91, 107, console::LightHead}, {87, 96, 87, 103, console::LightHead},
    {90, 96, 90, 107, console::LightHead}, {104, 96, 104, 103, console::LightHead}, {112, 97, 126, 98, console::LightTailReverse}, {112, 99, 112, 100, console::LightReverse},
    {113, 99, 126, 110, console::LightTailReverse}, {112, 101, 112, 101, console::LightBrake}, {112, 102, 112, 103, console::LightReverse}, {112, 104, 112, 104, console::LightBrake},
    {112, 105, 112, 105, console::LightReverse}, {112, 106, 112, 106, console::LightTailReverse}, {112, 107, 112, 109, console::LightReverse},
    // sindaccoi8bit128
    {65, 80, 68, 91, console::LightHead}, {73, 80, 86, 86, console::LightHead}, {89, 80, 94, 91, console::LightHead}, {69, 81, 72, 91, console::LightHead},
    {87, 81, 88, 91, console::LightHead}, {95, 81, 95, 91, console::LightHead}, {73, 87, 79, 87, console::LightHead}, {81, 87, 86, 91, console::LightHead},
    {73, 88, 78, 91, console::LightHead}, {79, 89, 80, 91, console::LightHead}, {113, 106, 125, 125, console::LightTailReverse}, {126, 107, 126, 107, console::LightReverse},
    {126, 108, 126, 109, console::LightBrake}, {126, 110, 126, 110, console::LightTailReverse}, {126, 111, 126, 111, console::LightBrake}, {126, 124, 126, 125, console::LightBrake},
    // freeway8bit128
    {12, 6, 12, 6, console::LightReverse}, {13, 6, 17, 25, console::LightHead}, {10, 7, 12, 9, console::LightHead}, {18, 7, 19, 24, console::LightHead},
    {20, 7, 20, 7, console::LightReverse}, {9, 8, 9, 24, console::LightHead}, {20, 8, 21, 23, console::LightHead}, {8, 9, 8, 23, console::LightHead},
    {22, 9, 22, 23, console::LightHead}, {7, 10, 7, 22, console::LightHead}, {10, 10, 10, 24, console::LightHead}, {12, 10, 12, 25, console::LightHead},
    {23, 10, 23, 22, console::LightHead}, {11, 11, 11, 25, console::LightHead}, {24, 11, 24, 20, console::LightHead}, {6, 12, 6, 21, console::LightHead},
    {5, 13, 5, 19, console::LightHead}, {25, 13, 25, 13, console::LightReverse}, {25, 14, 25, 17, console::LightHead}, {25, 18, 25, 18, console::LightReverse},
    {20, 24, 20, 24, console::LightHead}, {21, 24, 21, 24, console::LightReverse}, {18, 25, 18, 25, console::LightHead}, {19, 25, 19, 25, console::LightReverse},
    {96, 111, 111, 111, console::LightReverse}, {100, 112, 123, 126, console::LightTailReverse}, {124, 112, 125, 112, console::LightBrake}, {96, 113, 96, 113, console::LightBrake},
    {97, 113, 99, 126, console::LightTailReverse}, {124, 113, 127, 117, console::LightTailReverse}, {96, 114, 96, 123, console::LightTailReverse}, {124, 118, 126, 126, console::LightTailReverse},
    {127, 118, 127, 118, console::LightBrake}, {127, 119, 127, 124, console::LightTailReverse}, {96, 124, 96, 125, console::LightBrake}, {127, 125, 127, 125, console::LightBrake},
    {100, 127, 101, 127, console::LightBrake}, {102, 127, 108, 127, console::LightTailReverse}, {109, 127, 111, 127, console::LightBrake}, {112, 127, 112, 127, console::LightTailReverse},
    {113, 127, 113, 127, console::LightBrake}, {114, 127, 114, 127, console::LightTailReverse}, {115, 127, 115, 127, console::LightBrake}, {116, 127, 116, 127, console::LightTailReverse},
    {117, 127, 125, 127, console::LightBrake},
    // pizzaboy8bit128
    {96, 32, 127, 47, console::LightHead}, {112, 80, 127, 94, console::LightTailReverse}, {112, 95, 112, 95, console::LightBrake}, {113, 95, 116, 95, console::LightTailReverse},
    {117, 95, 118, 95, console::LightBrake}, {119, 95, 127, 95, console::LightTailReverse},
    // IJB_sportbike8bit128
    {64, 112, 95, 127, console::LightTailReverse}, {99, 112, 115, 116, console::LightHead}, {96, 113, 98, 127, console::LightHead}, {116, 113, 119, 122, console::LightHead},
    {120, 114, 122, 122, console::LightHead}, {123, 115, 124, 123, console::LightHead}, {125, 116, 125, 124, console::LightHead}, {100, 117, 115, 123, console::LightHead},
    {126, 117, 126, 123, console::LightHead}, {99, 118, 99, 127, console::LightHead}, {127, 118, 127, 122, console::LightHead}, {116, 123, 117, 123, console::LightHead},
    {100, 124, 112, 124, console::LightHead}, {124, 124, 124, 124, console::LightHead}, {100, 125, 105, 125, console::LightHead}, {109, 125, 110, 127, console::LightHead},
    {122, 125, 123, 125, console::LightHead}, {100, 126, 103, 127, console::LightHead}, {107, 126, 108, 127, console::LightHead}, {111, 126, 122, 126, console::LightHead},
    {104, 127, 106, 127, console::LightHead}, {111, 127, 119, 127, console::LightHead},
    // faggio8bit128
    {96, 32, 111, 46, console::LightHead}, {96, 47, 103, 47, console::LightHead}, {110, 47, 111, 47, console::LightHead}, {112, 80, 125, 88, console::LightTailReverse},
    {126, 80, 127, 80, console::LightBrake}, {126, 81, 127, 93, console::LightTailReverse}, {112, 89, 112, 91, console::LightBrake}, {113, 89, 125, 93, console::LightTailReverse},
    {112, 92, 112, 94, console::LightTailReverse}, {113, 94, 117, 94, console::LightTailReverse}, {118, 94, 124, 94, console::LightBrake}, {125, 94, 126, 94, console::LightTailReverse},
    {127, 94, 127, 94, console::LightBrake}, {112, 95, 115, 95, console::LightBrake},
    // sanchez8bit128
    {96, 112, 111, 127, console::LightHead}, {112, 112, 127, 127, console::LightTailReverse},
};
// Indexed by the cache ids in Models.hpp: first rect, count, reference width and height.
inline constexpr console::LightSet lightSets[] = {
    {0, 8, 128, 128}, // ferrarif3558bit128
    {8, 22, 128, 128}, // landstal8bit128
    {30, 6, 128, 128}, // idaho8bit128
    {36, 33, 128, 128}, // stinger8bit128
    {69, 17, 128, 128}, // linerun8bit128
    {86, 4, 128, 128}, // peren8bit128
    {90, 18, 128, 128}, // sentinel8bit128
    {108, 14, 128, 128}, // patriot8bit128
    {122, 14, 128, 128}, // firetruk8bit128
    {136, 15, 128, 128}, // trash8bit128
    {151, 13, 128, 128}, // stretch8bit128
    {164, 9, 128, 128}, // mananab8bit128
    {173, 15, 128, 128}, // infernus8bit128
    {188, 22, 128, 128}, // blista8bit128
    {210, 5, 128, 128}, // pony8bit128
    {215, 26, 128, 128}, // mule8bit128
    {241, 18, 128, 128}, // cheetah8bit128
    {259, 13, 128, 128}, // ambulan8bit128
    {272, 21, 128, 128}, // police8bit128
    {293, 16, 128, 128}, // moonbeam8bit128
    {309, 14, 128, 128}, // esperanto8bit128
    {323, 21, 128, 128}, // taxi8bit128
    {344, 11, 128, 128}, // kuruma8bit128
    {355, 31, 128, 128}, // bobcat8bit128
    {386, 5, 128, 128}, // mrwhoop8bit128
    {391, 21, 128, 128}, // bfinject8bit128
    {412, 18, 128, 128}, // enforcer8bit128
    {430, 17, 128, 128}, // securica8bit128
    {447, 3, 128, 128}, // banshee8bit128
    {450, 16, 128, 128}, // bus8bit128
    {466, 16, 128, 128}, // armytruk8bit128
    {482, 18, 128, 128}, // coach8bit128
    {500, 14, 128, 128}, // cabbie8bit128
    {514, 31, 128, 128}, // stallion8bit128
    {545, 7, 128, 128}, // rumpo8bit128
    {552, 18, 128, 128}, // mafia8bit128
    {570, 8, 128, 128}, // yardie8bit128
    {578, 33, 128, 128}, // yakuza8bit128
    {611, 51, 128, 128}, // diablos8bit128
    {662, 14, 128, 128}, // columb8bit128
    {676, 14, 128, 128}, // flatbed4bit128
    {690, 15, 128, 128}, // yankee8bit128
    {705, 25, 128, 128}, // IJB_brg
    {730, 19, 128, 128}, // typhoon_128_interior
    {749, 72, 128, 128}, // jm_firebirdintertior1256
    {821, 2, 128, 128}, // lotus8bit128
    {823, 23, 128, 128}, // hotrod8bit128
    {846, 16, 128, 128}, // sindaccoi8bit128
    {862, 45, 128, 128}, // freeway8bit128
    {907, 6, 128, 128}, // pizzaboy8bit128
    {913, 22, 128, 128}, // IJB_sportbike8bit128
    {935, 14, 128, 128}, // faggio8bit128
    {949, 2, 128, 128}, // sanchez8bit128
};
}
