#ifndef _D3DVTBL_H
#define _D3DVTBL_H

namespace IDirect3D8VTBL
{
    enum
    {
        QueryInterface = 0,
        AddRef = 1,
        Release = 2,
        RegisterSoftwareDevice = 3,
        GetAdapterCount = 4,
        GetAdapterIdentifier = 5,
        GetAdapterModeCount = 6,
        EnumAdapterModes = 7,
        GetAdapterDisplayMode = 8,
        CheckDeviceType = 9,
        CheckDeviceFormat = 10,
        CheckDeviceMultiSampleType = 11,
        CheckDepthStencilMatch = 12,
        GetDeviceCaps = 13,
        GetAdapterMonitor = 14,
        CreateDevice = 15
    };
}

namespace IDirect3D9VTBL
{
    enum
    {
        QueryInterface = 0,
        AddRef = 1,
        Release = 2,
        RegisterSoftwareDevice = 3,
        GetAdapterCount = 4,
        GetAdapterIdentifier = 5,
        GetAdapterModeCount = 6,
        EnumAdapterModes = 7,
        GetAdapterDisplayMode = 8,
        CheckDeviceType = 9,
        CheckDeviceFormat = 10,
        CheckDeviceMultiSampleType = 11,
        CheckDepthStencilMatch = 12,
        CheckDeviceFormatConversion = 13,
        GetDeviceCaps = 14,
        GetAdapterMonitor = 15,
        CreateDevice = 16
    };
}

namespace IDirect3DDevice8VTBL
{
    enum
    {
        QueryInterface = 0,
        AddRef = 1,
        Release = 2,
        TestCooperativeLevel = 3,
        GetAvailableTextureMem = 4,
        ResourceManagerDiscardBytes = 5,
        GetDirect3D = 6,
        GetDeviceCaps = 7,
        GetDisplayMode = 8,
        GetCreationParameters = 9,
        SetCursorProperties = 10,
        SetCursorPosition = 11,
        ShowCursor = 12,
        CreateAdditionalSwapChain = 13,
        Reset = 14,
        Present = 15,
        GetBackBuffer = 16,
        GetRasterStatus = 17,
        SetGammaRamp = 18,
        GetGammaRamp = 19,
        CreateTexture = 20,
        CreateVolumeTexture = 21,
        CreateCubeTexture = 22,
        CreateVertexBuffer = 23,
        CreateIndexBuffer = 24,
        CreateRenderTarget = 25,
        CreateDepthStencilSurface = 26,
        CreateImageSurface = 27,
        CopyRects = 28,
        UpdateTexture = 29,
        GetFrontBuffer = 30,
        SetRenderTarget = 31,
        GetRenderTarget = 32,
        GetDepthStencilSurface = 33,
        BeginScene = 34,
        EndScene = 35,
        Clear = 36,
        SetTransform = 37,
        GetTransform = 38,
        MultiplyTransform = 39,
        SetViewport = 40,
        GetViewport = 41,
        SetMaterial = 42,
        GetMaterial = 43,
        SetLight = 44,
        GetLight = 45,
        LightEnable = 46,
        GetLightEnable = 47,
        SetClipPlane = 48,
        GetClipPlane = 49,
        SetRenderState = 50,
        GetRenderState = 51,
        BeginStateBlock = 52,
        EndStateBlock = 53,
        ApplyStateBlock = 54,
        CaptureStateBlock = 55,
        DeleteStateBlock = 56,
        CreateStateBlock = 57,
        SetClipStatus = 58,
        GetClipStatus = 59,
        GetTexture = 60,
        SetTexture = 61,
        GetTextureStageState = 62,
        SetTextureStageState = 63,
        ValidateDevice = 64,
        GetInfo = 65,
        SetPaletteEntries = 66,
        GetPaletteEntries = 67,
        SetCurrentTexturePalette = 68,
        GetCurrentTexturePalette = 69,
        DrawPrimitive = 70,
        DrawIndexedPrimitive = 71,
        DrawPrimitiveUP = 72,
        DrawIndexedPrimitiveUP = 73,
        ProcessVertices = 74,
        CreateVertexShader = 75,
        SetVertexShader = 76,
        GetVertexShader = 77,
        DeleteVertexShader = 78,
        SetVertexShaderConstant = 79,
        GetVertexShaderConstant = 80,
        GetVertexShaderDeclaration = 81,
        GetVertexShaderFunction = 82,
        SetStreamSource = 83,
        GetStreamSource = 84,
        SetIndices = 85,
        GetIndices = 86,
        CreatePixelShader = 87,
        SetPixelShader = 88,
        GetPixelShader = 89,
        DeletePixelShader = 90,
        SetPixelShaderConstant = 91,
        GetPixelShaderConstant = 92,
        GetPixelShaderFunction = 93,
        DrawRectPatch = 94,
        DrawTriPatch = 95,
        DeletePatch = 96
    };
}

namespace IDirect3DDevice9VTBL
{
    enum
    {
        QueryInterface = 0,
        AddRef = 1,
        Release = 2,
        TestCooperativeLevel = 3,
        GetAvailableTextureMem = 4,
        EvictManagedResources = 5,
        GetDirect3D = 6,
        GetDeviceCaps = 7,
        GetDisplayMode = 8,
        GetCreationParameters = 9,
        SetCursorProperties = 10,
        SetCursorPosition = 11,
        ShowCursor = 12,
        CreateAdditionalSwapChain = 13,
        GetSwapChain = 14,
        GetNumberOfSwapChains = 15,
        Reset = 16,
        Present = 17,
        GetBackBuffer = 18,
        GetRasterStatus = 19,
        SetDialogBoxMode = 20,
        SetGammaRamp = 21,
        GetGammaRamp = 22,
        CreateTexture = 23,
        CreateVolumeTexture = 24,
        CreateCubeTexture = 25,
        CreateVertexBuffer = 26,
        CreateIndexBuffer = 27,
        CreateRenderTarget = 28,
        CreateDepthStencilSurface = 29,
        UpdateSurface = 30,
        UpdateTexture = 31,
        GetRenderTargetData = 32,
        GetFrontBufferData = 33,
        StretchRect = 34,
        ColorFill = 35,
        CreateOffscreenPlainSurface = 36,
        SetRenderTarget = 37,
        GetRenderTarget = 38,
        SetDepthStencilSurface = 39,
        GetDepthStencilSurface = 40,
        BeginScene = 41,
        EndScene = 42,
        Clear = 43,
        SetTransform = 44,
        GetTransform = 45,
        MultiplyTransform = 46,
        SetViewport = 47,
        GetViewport = 48,
        SetMaterial = 49,
        GetMaterial = 50,
        SetLight = 51,
        GetLight = 52,
        LightEnable = 53,
        GetLightEnable = 54,
        SetClipPlane = 55,
        GetClipPlane = 56,
        SetRenderState = 57,
        GetRenderState = 58,
        CreateStateBlock = 59,
        BeginStateBlock = 60,
        EndStateBlock = 61,
        SetClipStatus = 62,
        GetClipStatus = 63,
        GetTexture = 64,
        SetTexture = 65,
        GetTextureStageState = 66,
        SetTextureStageState = 67,
        GetSamplerState = 68,
        SetSamplerState = 69,
        ValidateDevice = 70,
        SetPaletteEntries = 71,
        GetPaletteEntries = 72,
        SetCurrentTexturePalette = 73,
        GetCurrentTexturePalette = 74,
        SetScissorRect = 75,
        GetScissorRect = 76,
        SetSoftwareVertexProcessing = 77,
        GetSoftwareVertexProcessing = 78,
        SetNPatchMode = 79,
        GetNPatchMode = 80,
        DrawPrimitive = 81,
        DrawIndexedPrimitive = 82,
        DrawPrimitiveUP = 83,
        DrawIndexedPrimitiveUP = 84,
        ProcessVertices = 85,
        CreateVertexDeclaration = 86,
        SetVertexDeclaration = 87,
        GetVertexDeclaration = 88,
        SetFVF = 89,
        GetFVF = 90,
        CreateVertexShader = 91,
        SetVertexShader = 92,
        GetVertexShader = 93,
        SetVertexShaderConstantF = 94,
        GetVertexShaderConstantF = 95,
        SetVertexShaderConstantI = 96,
        GetVertexShaderConstantI = 97,
        SetVertexShaderConstantB = 98,
        GetVertexShaderConstantB = 99,
        SetStreamSource = 100,
        GetStreamSource = 101,
        SetStreamSourceFreq = 102,
        GetStreamSourceFreq = 103,
        SetIndices = 104,
        GetIndices = 105,
        CreatePixelShader = 106,
        SetPixelShader = 107,
        GetPixelShader = 108,
        SetPixelShaderConstantF = 109,
        GetPixelShaderConstantF = 110,
        SetPixelShaderConstantI = 111,
        GetPixelShaderConstantI = 112,
        SetPixelShaderConstantB = 113,
        GetPixelShaderConstantB = 114,
        DrawRectPatch = 115,
        DrawTriPatch = 116,
        DeletePatch = 117,
        CreateQuery = 118
    };
}

#endif