name: GitHub Actions Build

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Build Solution
      uses: ./.github/workflows/build_all
      env:
        SCCOMPILE_PASSWORD: ${{ github.event_name == 'push' && github.ref_name == 'master' && secrets.SCCOMPILE_PASSWORD || '' }}
        CODE_SIGNING_PFX: ${{ github.event_name == 'push' && github.ref_name == 'master' && secrets.CODE_SIGNING_PFX || '' }}
        CODE_SIGNING_PASSWORD: ${{ github.event_name == 'push' && github.ref_name == 'master' && secrets.CODE_SIGNING_PASSWORD || '' }}
    - name: Update Tags
      continue-on-error: true
      if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
      uses: actions/github-script@v9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const sha = process.env.GITHUB_SHA
          if (!sha) {
            core.setFailed('Missing GITHUB_SHA')
            return
          }

          const tags = await github.paginate(github.rest.repos.listTags, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          })

          if (!tags.length) {
            core.info('No tags found to update.')
            return
          }

          for (const tag of tags) {
            const tagName = tag.name
            core.info(`Updating ${tagName} -> ${sha}`)
            await github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${tagName}`,
              sha,
              force: true
            })
          }
