name: Release By Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag of the release
        required: true
        type: choice
        options:
        - bully
        - burnout3
        - callofcthulhu
        - coldfear
        - condemned
        - da4
        - driv3r
        - driverpl
        - enterthematrix
        - farcry
        - fireteambravo1
        - fireteambravo2
        - fireteambravo3
        - gta1
        - gta2
        - gta3
        - gta3de
        - gtactwpsp
        - gtalcs
        - gtalcspsp
        - gtasa
        - gtasade
        - gtavc
        - gtavcde
        - gtavcs
        - gtavcspsp
        - gun
        - hd2
        - justcause
        - kingkong
        - kr
        - kr2
        - larush
        - mafia
        - mafiaxbox
        - manhunt
        - mp1
        - mp2
        - nfsc
        - nfsmw
        - nfsps
        - nfsu
        - nfsu2
        - nfsuc
        - nfstherun
        - onimusha3
        - paradisecracked
        - psiops
        - psychonauts
        - punisher
        - rdr
        - re0
        - re1
        - re2re3gc
        - re4
        - re5
        - re6
        - rerev
        - rerev2
        - sc
        - scarface
        - scc
        - scb
        - scct
        - scda
        - scdaps2
        - scdaxbox
        - sce
        - scpt
        - secondsight
        - sh2
        - sh3
        - sh4
        - sniperelite
        - sonicheroes
        - spyro
        - srs
        - thaw
        - thegodfather
        - thematrixpathofneo
        - thesaboteur
        - thesuffering
        - thewarriors
        - thps2
        - thps3
        - thps4
        - thug
        - thug2
        - tod
        - truecrimenyc
        - truecrimesola
        - xrd
        - usm

env:
  bully: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Bully_WidescreenFix /p:Configuration=Release
  burnout3: msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /t:Burnout3_PCSX2F_WidescreenFix /p:Configuration=Release
  callofcthulhu: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:CallOfCthulhu_WidescreenFix /p:Configuration=Release
  coldfear: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ColdFear_WidescreenFix /p:Configuration=Release
  condemned: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Condemned_WidescreenFix /p:Configuration=Release
  da4: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:DeerAvenger4_WidescreenFix /p:Configuration=Release
  driv3r: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Driv3r_WidescreenFix /p:Configuration=Release
  driverpl: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:DriverParallelLines_WidescreenFix /p:Configuration=Release
  enterthematrix: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:EnterTheMatrix_WidescreenFix /p:Configuration=Release
  farcry: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:FarCry_WidescreenFix /p:Configuration=Release
  fireteambravo1: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:SOCOM\\SOCOM_FireteamBravo_PPSSPP_FusionFix /p:Configuration=Release
  fireteambravo2: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:SOCOM\\SOCOM_FireteamBravo2_PPSSPP_FusionFix /p:Configuration=Release
  fireteambravo3: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:SOCOM\\SOCOM_FireteamBravo3_PPSSPP_FusionFix /p:Configuration=Release
  gta1: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTA1_WidescreenFix /p:Configuration=Release
  gta2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTA2_WidescreenFix /p:Configuration=Release
  gta3: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTA3_WidescreenFix /p:Configuration=Release
  gta3de: msbuild -m build/Win64.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTA3DE_FusionFix /p:Configuration=Release
  gtactwpsp: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTACTW_PPSSPP_FusionFix /p:Configuration=Release
  gtalcs: msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTALCS_PCSX2F_WidescreenFix /p:Configuration=Release
  gtalcspsp: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTALCS_PPSSPP_WidescreenFix /t:GrandTheftAuto\\GTALCS_PPSSPP_Project2DFX /t:GrandTheftAuto\\GTALCS_PPSSPP_ImVehLM /p:Configuration=Release
  gtasa: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTASA_WidescreenFix /p:Configuration=Release
  gtasade: msbuild -m build/Win64.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTASADE_FusionFix /p:Configuration=Release
  gtavc: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTAVC_WidescreenFix /p:Configuration=Release
  gtavcde: msbuild -m build/Win64.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTAVCDE_FusionFix /p:Configuration=Release
  gtavcs: msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTAVCS_PCSX2F_WidescreenFix /t:GrandTheftAuto\\GTAVCS_PCSX2F_Project2DFX /t:GrandTheftAuto\\GTAVCS_PCSX2F_ImVehLM /p:Configuration=Release
  gtavcspsp: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:GrandTheftAuto\\GTAVCS_PPSSPP_WidescreenFix /t:GrandTheftAuto\\GTAVCS_PPSSPP_Project2DFX /t:GrandTheftAuto\\GTAVCS_PPSSPP_ImVehLM /t:GrandTheftAuto\\GTAVCS_PPSSPP_GamepadIcons /p:Configuration=Release
  gun: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Gun_WidescreenFix /p:Configuration=Release
  hd2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:HiddenandDangerous2_WidescreenFix /p:Configuration=Release
  justcause: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:JustCause_WidescreenFix /p:Configuration=Release
  kingkong: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:KingKong_WidescreenFix /p:Configuration=Release
  kr: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:KnightRider_WidescreenFix /p:Configuration=Release && msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /t:KnightRider_PCSX2F_WidescreenFix /p:Configuration=Release
  kr2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:KnightRider2_WidescreenFix /p:Configuration=Release
  larush: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:LARush_WidescreenFix /p:Configuration=Release
  mafia: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Mafia_WidescreenFix /p:Configuration=Release
  mafiaxbox: msbuild -m build/CXBXR.WidescreenFixesPack.slnx /t:Mafia_CXBXR_WidescreenFix /p:Configuration=Release
  manhunt: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Manhunt_WidescreenFix /p:Configuration=Release
  mp1: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:MaxPayne\\MaxPayne_WidescreenFix /p:Configuration=Release
  mp2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:MaxPayne\\MaxPayne2_WidescreenFix /p:Configuration=Release
  nfsc: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSCarbon_WidescreenFix /p:Configuration=Release
  nfsmw: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSMostWanted_WidescreenFix /p:Configuration=Release
  nfsps: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSProStreet_FusionFix /p:Configuration=Release
  nfsu: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSUnderground_WidescreenFix /p:Configuration=Release
  nfsu2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSUnderground2_WidescreenFix /p:Configuration=Release
  nfsuc: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSUndercover_FusionFix /p:Configuration=Release
  nfstherun: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:NeedForSpeed\\NFSTheRun_FusionFix /p:Configuration=Release
  onimusha3: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Onimusha3_WidescreenFix /p:Configuration=Release
  paradisecracked: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ParadiseCracked_WidescreenFix /p:Configuration=Release
  psiops: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:PsiOpsTheMindgateConspiracy_WidescreenFix /p:Configuration=Release
  psychonauts: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Psychonauts_WidescreenFix /p:Configuration=Release
  punisher: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ThePunisher_WidescreenFix /p:Configuration=Release
  rdr: msbuild -m build/Win64.WidescreenFixesPack.slnx /t:RedDeadRedemption_FusionFix /p:Configuration=Release
  re0: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil0_FusionFix /p:Configuration=Release
  re1: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil_FusionFix /p:Configuration=Release
  re2re3gc: msbuild -m build/Dolphin.WidescreenFixesPack.slnx /t:ResidentEvil2_RE3_Dolphin_FusionFix /p:Configuration=Release
  re4: msbuild -m build/Win64.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil4_FusionFix /p:Configuration=Release
  re5: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil5_FusionFix /p:Configuration=Release
  re6: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvil6_FusionFix /p:Configuration=Release
  rerev: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvilRevelations_FusionFix /p:Configuration=Release
  rerev2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:ResidentEvil\\ResidentEvilRevelations2_FusionFix /p:Configuration=Release
  sc: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCell_WidescreenFix /p:Configuration=Release
  scarface: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:Scarface_FusionFix /p:Configuration=Release
  scc: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellConviction_FusionFix /p:Configuration=Release
  scb: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellBlacklist_FusionFix /p:Configuration=Release
  scct: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellChaosTheory_WidescreenFix /p:Configuration=Release
  scda: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellDoubleAgent_WidescreenFix /p:Configuration=Release
  scdaps2: msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /t:SplinterCellDoubleAgent_PCSX2F_WidescreenFix /p:Configuration=Release
  scdaxbox: msbuild -m build/CXBXR.WidescreenFixesPack.slnx /t:SplinterCellDoubleAgent_CXBXR_WidescreenFix /p:Configuration=Release
  sce: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:SplinterCellEssentials_PPSSPP_FusionFix /p:Configuration=Release
  scpt: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SplinterCell\\SplinterCellPandoraTomorrow_WidescreenFix /p:Configuration=Release
  secondsight: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SecondSight_WidescreenFix /p:Configuration=Release
  sh2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SilentHill\\SilentHill2_WidescreenFix /p:Configuration=Release
  sh3: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SilentHill\\SilentHill3_WidescreenFix /p:Configuration=Release
  sh4: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SilentHill\\SilentHill4_WidescreenFix /p:Configuration=Release
  sniperelite: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SniperElite_WidescreenFix /p:Configuration=Release
  sonicheroes: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:SonicHeroes_WidescreenFix /p:Configuration=Release
  spyro: msbuild -m build/Win64.WidescreenFixesPack.slnx /t:SpyroReignitedTrilogy_WidescreenFix /p:Configuration=Release
  srs: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:StreetRacingSyndicate_WidescreenFix /p:Configuration=Release
  thegodfather: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheGodfather_WidescreenFix /p:Configuration=Release
  thematrixpathofneo: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheMatrixPathOfNeo_WidescreenFix /p:Configuration=Release
  thesaboteur: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheSaboteur_FusionFix /p:Configuration=Release
  thesuffering: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TheSuffering_WidescreenFix /p:Configuration=Release
  thewarriors: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:TheWarriors_PPSSPP_FusionFix /p:Configuration=Release
  thps2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksProSkater2_WidescreenFix /p:Configuration=Release
  thps3: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksProSkater3_WidescreenFix /p:Configuration=Release
  thps4: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksProSkater4_WidescreenFix /p:Configuration=Release
  thug: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksUnderground_WidescreenFix /p:Configuration=Release
  thug2: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksUnderground2_WidescreenFix /p:Configuration=Release
  thaw: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TonyHawks\\TonyHawksAmericanWasteland_WidescreenFix /p:Configuration=Release
  tod: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TotalOverdose_WidescreenFix /p:Configuration=Release
  truecrimenyc: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TrueCrimeNewYorkCity_WidescreenFix /p:Configuration=Release && msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /t:TrueCrimeNewYorkCity_PCSX2F_WidescreenFix /p:Configuration=Release
  truecrimesola: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:TrueCrimeStreetsofLA_WidescreenFix /p:Configuration=Release
  xrd: msbuild -m build/PPSSPP.WidescreenFixesPack.slnx /t:PPSSPP_XboxRainDroplets /p:Configuration=Release && msbuild -m build/PCSX2F.WidescreenFixesPack.slnx /t:PCSX2F_XboxRainDroplets /p:Configuration=Release
  usm: msbuild -m build/Win32.WidescreenFixesPack.slnx /t:UltimateSpiderMan_WidescreenFix /p:Configuration=Release

jobs:
  setup_project_name:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.prj_name.outputs.project_name }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: prj_name
        run: |
          echo "project_name=${{ env[inputs.tag_name] }}" >> $GITHUB_OUTPUT
  call-workflow-passing-data:
    needs: setup_project_name
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: ${{ inputs.tag_name }}
      project: ${{ needs.setup_project_name.outputs.project_name }}
    secrets: inherit
